<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Gage r&amp;R | industRial data science</title>
  <meta name="description" content="Gage r&amp;R | industRial data science" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Gage r&amp;R | industRial data science" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Gage r&amp;R | industRial data science" />
  
  
  

<meta name="author" content="João Ramalho" />


<meta name="date" content="2021-01-27" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="MSA.html"/>
<link rel="next" href="conclusions.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">industRial data science</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="part"><span><b>I FRAMEWORK</b></span></li>
<li class="chapter" data-level="" data-path="six-sigma.html"><a href="six-sigma.html"><i class="fa fa-check"></i>Six Sigma</a>
<ul>
<li class="chapter" data-level="" data-path="six-sigma.html"><a href="six-sigma.html#cause-and-effect-diagrams"><i class="fa fa-check"></i>Cause and Effect diagrams</a></li>
<li class="chapter" data-level="" data-path="six-sigma.html"><a href="six-sigma.html#pareto-chart"><i class="fa fa-check"></i>Pareto chart</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html"><i class="fa fa-check"></i>Statistics</a>
<ul>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#descriptive-statistics"><i class="fa fa-check"></i>Descriptive statistics</a></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#statistical-distributions"><i class="fa fa-check"></i>Statistical distributions</a></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#statistical-tests"><i class="fa fa-check"></i>Statistical tests</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html"><i class="fa fa-check"></i>R</a></li>
<li class="part"><span><b>II CASE STUDIES</b></span></li>
<li class="chapter" data-level="" data-path="AQL.html"><a href="AQL.html"><i class="fa fa-check"></i>AQL - Acceptance Sampling</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html"><i class="fa fa-check"></i>DOE - Design of Experiments</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#simple-comparative-experiments"><i class="fa fa-check"></i>Simple comparative experiments</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-cement-example"><i class="fa fa-check"></i>The Cement example</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#homogeneity-of-variances-test-levene-test"><i class="fa fa-check"></i>Homogeneity of variances test (Levene Test)</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#sample-size-calculation"><i class="fa fa-check"></i>Sample size calculation</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#t-test-paired"><i class="fa fa-check"></i>t-test paired</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#single-factor-designs"><i class="fa fa-check"></i>Single factor designs</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#plasma-etching-example"><i class="fa fa-check"></i>Plasma etching example</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#analysis-of-variance"><i class="fa fa-check"></i>Analysis of variance</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#single-factor-anova-fixed-effects-model"><i class="fa fa-check"></i>Single factor Anova, fixed effects model</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#model-adequacy-check"><i class="fa fa-check"></i>Model adequacy check</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#residuals-normality-check-outliers"><i class="fa fa-check"></i>Residuals normality check &amp; outliers</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#plot-of-residuals-in-time-sequence"><i class="fa fa-check"></i>Plot of residuals in time sequence</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#plot-of-residuals-versus-fitted-values"><i class="fa fa-check"></i>Plot of residuals versus fitted values</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#equality-of-variances-test-barletts-test"><i class="fa fa-check"></i>Equality of variances test (Barlett’s test)</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#tuckeys-pairwise-comparison-test"><i class="fa fa-check"></i>Tuckey’s pairwise comparison test</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#fishers-lsd---pairwise-comparison-test"><i class="fa fa-check"></i>Fisher’s LSD - pairwise comparison test</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#practical-interpretation-of-results"><i class="fa fa-check"></i>Practical interpretation of results</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#linear-model"><i class="fa fa-check"></i>Linear model</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#linear-model-plot"><i class="fa fa-check"></i>Linear model plot</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#predicting-new-values"><i class="fa fa-check"></i>Predicting new values</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#r²-coefficient-of-determination"><i class="fa fa-check"></i>R², coefficient of determination</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#sample-size-calculation-1"><i class="fa fa-check"></i>Sample size calculation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#two-factors-anova-fixed-effects-model"><i class="fa fa-check"></i>two-factors ANOVA, fixed effects model</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#battery-life-example"><i class="fa fa-check"></i>Battery life example</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#analysis-of-variance-1"><i class="fa fa-check"></i>Analysis of variance</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#doe-and-anova-plots"><i class="fa fa-check"></i>DoE and Anova plots</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#r²-coefficient-of-determination-1"><i class="fa fa-check"></i>R², coefficient of determination</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#model-adequacy-checking"><i class="fa fa-check"></i>Model adequacy checking</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#residuals-normality-check-outliers-1"><i class="fa fa-check"></i>Residuals normality check &amp; outliers</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#plot-of-residuals-versus-fitted-values-1"><i class="fa fa-check"></i>Plot of residuals versus fitted values</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#sample-size-calculation-2"><i class="fa fa-check"></i>Sample size calculation</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#model-with-no-interaction"><i class="fa fa-check"></i>Model with no interaction</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#general-factorial-design"><i class="fa fa-check"></i>General factorial design</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#soft-drink-bottling-example"><i class="fa fa-check"></i>Soft Drink bottling example</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#analysis-of-variance-2"><i class="fa fa-check"></i>Analysis of variance</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#residuals-analysis"><i class="fa fa-check"></i>Residuals analysis</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#doe-plots"><i class="fa fa-check"></i>DoE plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-2k-factorial-designs"><i class="fa fa-check"></i>The 2^k factorial designs</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-22-factorial-design"><i class="fa fa-check"></i>The 2^2 Factorial Design</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-chemical-process-example"><i class="fa fa-check"></i>The Chemical Process example</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#anova"><i class="fa fa-check"></i>Anova</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#correlation-of-the-outputs"><i class="fa fa-check"></i>Correlation of the outputs</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#correlation-matrix"><i class="fa fa-check"></i>Correlation matrix</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#network-diagrams"><i class="fa fa-check"></i>Network diagrams</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#regression-model-prediction"><i class="fa fa-check"></i>Regression model / Prediction</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#response-surface"><i class="fa fa-check"></i>Response surface</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-23-factorial-design"><i class="fa fa-check"></i>The 2^3 Factorial Design</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-plasma-etching-example"><i class="fa fa-check"></i>The plasma etching example</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#anova-1"><i class="fa fa-check"></i>Anova</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#regression-model-prediction-1"><i class="fa fa-check"></i>Regression model / Prediction</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#reduced-model"><i class="fa fa-check"></i>Reduced model</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#doe-plots-1"><i class="fa fa-check"></i>DoE plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-general-2k-design"><i class="fa fa-check"></i>The general 2^k design</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#calculating-the-number-combinations"><i class="fa fa-check"></i>Calculating the number combinations</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#relationship-coded-vs-natural-variables"><i class="fa fa-check"></i>Relationship coded vs natural variables</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#single-replicate-2k-design"><i class="fa fa-check"></i>Single replicate 2^k design</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-filtration-example"><i class="fa fa-check"></i>The Filtration example</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#anova-2"><i class="fa fa-check"></i>Anova</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#linear-regression---plot-of-effects"><i class="fa fa-check"></i>Linear regression - Plot of effects</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#doe-plots-2"><i class="fa fa-check"></i>DoE plots</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#anova-reduced-model-significant-effects-only"><i class="fa fa-check"></i>Anova reduced model (significant effects only)</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#linear-regression---reduced-model"><i class="fa fa-check"></i>Linear regression - reduced model</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#residuals-normality-check"><i class="fa fa-check"></i>Residuals normality check</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#two-level-fractional-factorial-designs"><i class="fa fa-check"></i>Two level fractional factorial designs</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-one-half-fraction-of-th-2k-design"><i class="fa fa-check"></i>The One-Half Fraction of th 2k Design</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-filtration-example-modified"><i class="fa fa-check"></i>The filtration example (modified)</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#anova-3"><i class="fa fa-check"></i>Anova</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#analysis-of-covariance"><i class="fa fa-check"></i>Analysis of Covariance</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#approach"><i class="fa fa-check"></i>Approach</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#case-study"><i class="fa fa-check"></i>Case study</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#ancova"><i class="fa fa-check"></i>Ancova</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#comparison-with-anova"><i class="fa fa-check"></i>Comparison with anova</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#potential-applications"><i class="fa fa-check"></i>Potential applications</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html"><i class="fa fa-check"></i>MSA - Measurement System Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html#case-study-1"><i class="fa fa-check"></i>Case study</a></li>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html#robustness"><i class="fa fa-check"></i>Robustness</a></li>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html#linearity"><i class="fa fa-check"></i>Linearity</a></li>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html#loq---limit-of-quantification"><i class="fa fa-check"></i>LoQ - Limit of quantification</a></li>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html#trueness"><i class="fa fa-check"></i>Trueness</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="gage-rr.html"><a href="gage-rr.html"><i class="fa fa-check"></i>Gage r&amp;R</a>
<ul>
<li class="chapter" data-level="" data-path="gage-rr.html"><a href="gage-rr.html#objective"><i class="fa fa-check"></i>Objective</a></li>
<li class="chapter" data-level="" data-path="gage-rr.html"><a href="gage-rr.html#data-loading"><i class="fa fa-check"></i>Data loading</a></li>
<li class="chapter" data-level="" data-path="gage-rr.html"><a href="gage-rr.html#stats-package"><i class="fa fa-check"></i>Stats package</a></li>
<li class="chapter" data-level="" data-path="gage-rr.html"><a href="gage-rr.html#six-sigma-package"><i class="fa fa-check"></i>Six Sigma package</a>
<ul>
<li class="chapter" data-level="" data-path="gage-rr.html"><a href="gage-rr.html#anova-table"><i class="fa fa-check"></i>Anova table</a></li>
<li class="chapter" data-level="" data-path="gage-rr.html"><a href="gage-rr.html#variance-components-table"><i class="fa fa-check"></i>Variance components table</a></li>
<li class="chapter" data-level="" data-path="gage-rr.html"><a href="gage-rr.html#study-variation-table"><i class="fa fa-check"></i>Study Variation table</a></li>
<li class="chapter" data-level="" data-path="gage-rr.html"><a href="gage-rr.html#plots"><i class="fa fa-check"></i>Plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="gage-rr.html"><a href="gage-rr.html#concern-negative-components-of-variation"><i class="fa fa-check"></i>Concern: negative Components of Variation</a></li>
<li class="chapter" data-level="" data-path="gage-rr.html"><a href="gage-rr.html#concern-analysis-beyond-two-factors"><i class="fa fa-check"></i>Concern: analysis beyond two factors</a></li>
<li class="chapter" data-level="" data-path="gage-rr.html"><a href="gage-rr.html#other-concerns"><i class="fa fa-check"></i>Other concerns</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="conclusions.html"><a href="conclusions.html"><i class="fa fa-check"></i>Conclusions</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a>
<ul>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html#mu---measurement-incertainty"><i class="fa fa-check"></i>MU - Measurement incertainty</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="SPC.html"><a href="SPC.html"><i class="fa fa-check"></i>SPC - Statistical Process Control</a>
<ul>
<li class="chapter" data-level="" data-path="SPC.html"><a href="SPC.html#case-study-2"><i class="fa fa-check"></i>Case study</a></li>
<li class="chapter" data-level="" data-path="SPC.html"><a href="SPC.html#xbar-and-r-charts"><i class="fa fa-check"></i>xbar and R charts</a></li>
<li class="chapter" data-level="" data-path="SPC.html"><a href="SPC.html#warnings-and-specification-limits"><i class="fa fa-check"></i>Warnings and specification limits</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Cpk.html"><a href="Cpk.html"><i class="fa fa-check"></i>CPK - Process Capability Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="Cpk.html"><a href="Cpk.html#case-study-3"><i class="fa fa-check"></i>Case study</a></li>
<li class="chapter" data-level="" data-path="Cpk.html"><a href="Cpk.html#process-capability-chart"><i class="fa fa-check"></i>Process Capability chart</a></li>
</ul></li>
<li class="part"><span><b>III TOOLBOX</b></span></li>
<li class="chapter" data-level="" data-path="Rpck.html"><a href="Rpck.html"><i class="fa fa-check"></i>R Packages</a>
<ul>
<li class="chapter" data-level="" data-path="Rpck.html"><a href="Rpck.html#industrial-data-science-specific-packages"><i class="fa fa-check"></i>Industrial Data Science specific packages</a>
<ul>
<li class="chapter" data-level="" data-path="Rpck.html"><a href="Rpck.html#six-sigma-1"><i class="fa fa-check"></i>six sigma</a></li>
<li class="chapter" data-level="" data-path="Rpck.html"><a href="Rpck.html#ggspc"><i class="fa fa-check"></i>ggspc</a></li>
<li class="chapter" data-level="" data-path="Rpck.html"><a href="Rpck.html#qcc"><i class="fa fa-check"></i>qcc</a></li>
<li class="chapter" data-level="" data-path="Rpck.html"><a href="Rpck.html#qicharts2"><i class="fa fa-check"></i>qicharts2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rpck.html"><a href="Rpck.html#other-important-packages"><i class="fa fa-check"></i>Other important packages</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html"><i class="fa fa-check"></i>Datasets</a></li>
<li class="chapter" data-level="" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">indust<b style='color:#4775d1'>R</b>ial data science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="gage-rr" class="section level1">
<h1>Gage r&amp;R</h1>
<div id="objective" class="section level2">
<h2>Objective</h2>
<p>The objective of this document is to assess the scope of utilisation of the r&amp;R for a measurement method using the Six Sigma package from R. A comparison with base R anova and with Minitab r&amp;R is also done. This report is accompaigned by a “CheatSheet” excel file with formulas allowing to understand and easily confirm the SixSigma package calculations.</p>
</div>
<div id="data-loading" class="section level2">
<h2>Data loading</h2>
<p>We use here the data from the pod volume method validation:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="gage-rr.html#cb170-1" aria-hidden="true" tabindex="-1"></a>repea_repro <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;data/rnR_case_study.xlsx&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">clean_names</span>() <span class="sc">%&gt;%</span></span>
<span id="cb170-2"><a href="gage-rr.html#cb170-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">size =</span> <span class="fu">as_factor</span>(size)) <span class="sc">%&gt;%</span></span>
<span id="cb170-3"><a href="gage-rr.html#cb170-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pod =</span> <span class="fu">as_factor</span>(pod)) <span class="sc">%&gt;%</span></span>
<span id="cb170-4"><a href="gage-rr.html#cb170-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">operator =</span> <span class="fu">as_factor</span>(operator)) <span class="sc">%&gt;%</span></span>
<span id="cb170-5"><a href="gage-rr.html#cb170-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">day =</span> <span class="fu">fct_inorder</span>(day))</span></code></pre></div>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="gage-rr.html#cb171-1" aria-hidden="true" tabindex="-1"></a>repea_repro_L <span class="ot">&lt;-</span> repea_repro <span class="sc">%&gt;%</span></span>
<span id="cb171-2"><a href="gage-rr.html#cb171-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(size <span class="sc">==</span> <span class="st">&quot;L&quot;</span>)</span></code></pre></div>
</div>
<div id="stats-package" class="section level2">
<h2>Stats package</h2>
<p>We’re feeding the aov function from the stats package with operator and pod factors.</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="gage-rr.html#cb172-1" aria-hidden="true" tabindex="-1"></a>repea_repro_L_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb172-2"><a href="gage-rr.html#cb172-2" aria-hidden="true" tabindex="-1"></a>  volume_mm3 <span class="sc">~</span> (</span>
<span id="cb172-3"><a href="gage-rr.html#cb172-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># main effects</span></span>
<span id="cb172-4"><a href="gage-rr.html#cb172-4" aria-hidden="true" tabindex="-1"></a>    pod <span class="sc">+</span></span>
<span id="cb172-5"><a href="gage-rr.html#cb172-5" aria-hidden="true" tabindex="-1"></a>    operator <span class="sc">+</span></span>
<span id="cb172-6"><a href="gage-rr.html#cb172-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 2nd order interactions</span></span>
<span id="cb172-7"><a href="gage-rr.html#cb172-7" aria-hidden="true" tabindex="-1"></a>    operator<span class="sc">:</span>pod</span>
<span id="cb172-8"><a href="gage-rr.html#cb172-8" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb172-9"><a href="gage-rr.html#cb172-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> repea_repro_L</span>
<span id="cb172-10"><a href="gage-rr.html#cb172-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb172-11"><a href="gage-rr.html#cb172-11" aria-hidden="true" tabindex="-1"></a>repea_repro_L_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(repea_repro_L_lm)</span>
<span id="cb172-12"><a href="gage-rr.html#cb172-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(repea_repro_L_aov)</span></code></pre></div>
<pre><code>##               Df Sum Sq Mean Sq F value Pr(&gt;F)    
## pod            4 170707   42677 271.450 &lt;2e-16 ***
## operator       2   1313     657   4.176 0.0167 *  
## pod:operator   8   1122     140   0.892 0.5237    
## Residuals    210  33016     157                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="six-sigma-package" class="section level2">
<h2>Six Sigma package</h2>
<p>Below we’re recreating the same analysis with the ss.rr function from the Six Sigma package. As the function allows to input the limits we’re also providing in the function arguments the current upper and lower limit of the specification.</p>
<p>Pod L 18’000mm3 +/- 250mm3 (18.0ml +/- 0.25ml)</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="gage-rr.html#cb174-1" aria-hidden="true" tabindex="-1"></a>repea_repro_L_rr <span class="ot">&lt;-</span> <span class="fu">ss.rr</span>(</span>
<span id="cb174-2"><a href="gage-rr.html#cb174-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> repea_repro_L, </span>
<span id="cb174-3"><a href="gage-rr.html#cb174-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">var =</span> volume_mm3, </span>
<span id="cb174-4"><a href="gage-rr.html#cb174-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">part =</span> pod, </span>
<span id="cb174-5"><a href="gage-rr.html#cb174-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">appr =</span> operator, </span>
<span id="cb174-6"><a href="gage-rr.html#cb174-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">alphaLim =</span> <span class="dv">1</span>,</span>
<span id="cb174-7"><a href="gage-rr.html#cb174-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># errorTerm = </span></span>
<span id="cb174-8"><a href="gage-rr.html#cb174-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">&quot;Keyence KEYENCE VR-5200</span><span class="sc">\n</span><span class="st">r&amp;R for Pod Volume&quot;</span>,</span>
<span id="cb174-9"><a href="gage-rr.html#cb174-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">sub =</span> <span class="st">&quot;Pod L&quot;</span>,</span>
<span id="cb174-10"><a href="gage-rr.html#cb174-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">lsl =</span> <span class="dv">17075</span>,</span>
<span id="cb174-11"><a href="gage-rr.html#cb174-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">usl =</span> <span class="dv">18025</span></span>
<span id="cb174-12"><a href="gage-rr.html#cb174-12" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Complete model (with interaction):
## 
##                Df Sum Sq Mean Sq F value   Pr(&gt;F)
## pod             4 170707   42677 304.181 9.06e-09
## operator        2   1313     657   4.680   0.0451
## pod:operator    8   1122     140   0.892   0.5237
## Repeatability 210  33016     157                 
## Total         224 206158                         
## 
## alpha for removing interaction: 1 
## 
## Gage R&amp;R
## 
##                      VarComp %Contrib
## Total Gage R&amp;R     164.10066    14.79
##   Repeatability    157.21730    14.17
##   Reproducibility    6.88336     0.62
##     operator         6.88336     0.62
## pod:operator         0.00000     0.00
## Part-To-Part       945.25173    85.21
## Total Variation   1109.35239   100.00
## 
##                      VarComp    StdDev  StudyVar %StudyVar %Tolerance
## Total Gage R&amp;R     164.10066 12.810178  76.86107     38.46       8.09
##   Repeatability    157.21730 12.538632  75.23179     37.65       7.92
##   Reproducibility    6.88336  2.623616  15.74170      7.88       1.66
##     operator         6.88336  2.623616  15.74170      7.88       1.66
## pod:operator         0.00000  0.000000   0.00000      0.00       0.00
## Part-To-Part       945.25173 30.744946 184.46968     92.31      19.42
## Total Variation   1109.35239 33.306942 199.84165    100.00      21.04
## 
## Number of Distinct Categories = 3</code></pre>
<p><img src="IndustRialds_files/figure-html/unnamed-chunk-60-1.png" width="80%" /></p>
<p>We can observe that the SixSigma package recreates exactly the same anova table, just calling Repeatability to the Residuals and adding an additional line with the total degrees of freedom and the total sum of squares.</p>
<p>Note that the argument alphaLim has been set to 1 to avoid suppressing the interaction which is in this case non significative.</p>
<div id="anova-table" class="section level3">
<h3>Anova table</h3>
<ul>
<li>pod (Part): The variation that comes from the parts, with 5 levels in this case</li>
<li>operator: The variation that comes from the operators, with 3 levels in this case</li>
<li>Operator*Part: The variation that comes from the operator and part interaction. An interaction exists when an operator measures different parts differently.</li>
<li>repeatability (or error, or residuals): The variation that is not explained by part, operator, or the operator and part interaction.
Variance</li>
<li>n: number of replicants, 15 in this case (not presented in the table)</li>
</ul>
<p>These are used for establishing the Variance Components and Study Variation tables that are exactly the same that are obtained with Minitab.</p>
</div>
<div id="variance-components-table" class="section level3">
<h3>Variance components table</h3>
<p>Variance components assess the amount of variation contributed by each source of measurement error, plus the contribution of part-to-part variability.</p>
<ul>
<li>total gage r&amp;R: the sum of the repeatability and the reproducibility variance components</li>
<li>repeatability: how much variability is caused by the measurement device (the same operator measures the same part many times, using the same gage). The repeteability can be measured directly from the Anova table from the residual mean squares</li>
<li>reproducibility: how much variation is caused by the differences between operators (different operators measure the same part many times, using the same gage)</li>
<li>operators: the operators part of the reproducibility is the operators variation minus the interaction divided by the number of different parts times the replicants (zero if negative)</li>
<li>parts:operators: the interaction part of of the reproducibility is the interaction minus the repeatability divided by the number of replicants (zero if negative)</li>
<li>part-to-part: the variability due to different parts. Ideally, very little should be due to repeatability and reproducibility. Differences between parts should account for most of the variability (when the %Contribution from part-to-part variation is high, the measurement system can reliably distinguish between parts).</li>
</ul>
<p>The sum of the individual variance components equals the total variation.</p>
<p><strong>Criteria for measurement system acceptance:</strong></p>
<p>To evaluate your process variation, compare the Total Gage R&amp;R contribution in the %Contrib column with the values in the list below:</p>
<ul>
<li>Less than 1%: the measurement system is acceptable</li>
<li>Between 1% and 9%: the measurement system is acceptable depending on the application, the cost of the measurement device, cost of repair, or other factors</li>
<li>Greater than 9%: the measurement system is not acceptable and should be improved.</li>
</ul>
</div>
<div id="study-variation-table" class="section level3">
<h3>Study Variation table</h3>
<p>The study variation table is established by calculating the square root of each variance (the standard deviation) and by multiplying it by 6 (the six sigma) and then again by comparing each variation with the total variation. Standard deviations are usualy more speaking to the industry professionals. This table also provides a comparison with the specification.</p>
<p>According to the Automotive Industry Action Group <a href="https://www.aiag.org/">AIAG</a> guidelines, if your system variation is less than 10% of the process variation, then it is acceptable.</p>
<p>To evaluate your process variation, compare the Total Gage R&amp;R contribution in the %StudyVar column with the values in the list below:</p>
<ul>
<li>Less than 10%: the measurement system is acceptable</li>
<li>Between 10% and 30%: the measurement system is acceptable depending on the application, the cost of the measurement device, cost of repair, or other factors</li>
<li>Greater that 30%: the measurement system is not acceptable and should be improved.</li>
</ul>
<p>If the p-value for the operator and part interaction is 0.05 or higher, the system removes the interaction because it is not significant and generates a second ANOVA table without the interaction.</p>
<p>The AIAG also states that the number of distinct categories into which the measurement system divides process output should be greater or equal to 5.</p>
<p>In our specific example we observe that the device cannot be accepted as the Study variation for the Total Gage r&amp;R is 38.46% thus much higher than 30%. Furhtermore the number of distinc categories is only of 3. The part to part variation is high which is normal and the total variation rather low when compared with the specification (but this is not enough as the specification is process dependent).</p>
</div>
<div id="plots" class="section level3">
<h3>Plots</h3>
<p>The Six Sigma package plots are similar to the interaction plots provided by other DoE packages but don’t have error bars. These can nevertheless easily be established on a needed basis as in the example below where we’re recreating the pod:operator interaction plot with a +/- 1 standard deviation error bars.</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="gage-rr.html#cb176-1" aria-hidden="true" tabindex="-1"></a>repea_repro_L <span class="sc">%&gt;%</span></span>
<span id="cb176-2"><a href="gage-rr.html#cb176-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(pod, operator) <span class="sc">%&gt;%</span></span>
<span id="cb176-3"><a href="gage-rr.html#cb176-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">vol_mean =</span> <span class="fu">mean</span>(volume_mm3), <span class="at">vol_sd =</span> <span class="fu">sd</span>(volume_mm3)) <span class="sc">%&gt;%</span></span>
<span id="cb176-4"><a href="gage-rr.html#cb176-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> pod, <span class="at">y =</span> vol_mean, <span class="at">color =</span> operator)) <span class="sc">+</span></span>
<span id="cb176-5"><a href="gage-rr.html#cb176-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">group =</span> operator), <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb176-6"><a href="gage-rr.html#cb176-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> operator, <span class="at">linetype =</span> operator)) <span class="sc">+</span></span>
<span id="cb176-7"><a href="gage-rr.html#cb176-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> vol_mean <span class="sc">-</span> vol_sd, </span>
<span id="cb176-8"><a href="gage-rr.html#cb176-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ymax =</span> vol_mean <span class="sc">+</span> vol_sd),</span>
<span id="cb176-9"><a href="gage-rr.html#cb176-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb176-10"><a href="gage-rr.html#cb176-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">10000</span>, <span class="dv">20000</span>, <span class="dv">10</span>),</span>
<span id="cb176-11"><a href="gage-rr.html#cb176-11" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">label_number</span>(<span class="at">big.mark =</span> <span class="st">&quot;&#39;&quot;</span>)) <span class="sc">+</span></span>
<span id="cb176-12"><a href="gage-rr.html#cb176-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>(<span class="at">option =</span> <span class="st">&quot;C&quot;</span>, <span class="at">begin =</span> <span class="fl">0.1</span>, <span class="at">end =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb176-13"><a href="gage-rr.html#cb176-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># coord_cartesian(ylim = c(17950, 18150)) +</span></span>
<span id="cb176-14"><a href="gage-rr.html#cb176-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="at">geom =</span> <span class="st">&quot;text&quot;</span>, <span class="at">x =</span> <span class="cn">Inf</span>, <span class="at">y =</span> <span class="sc">-</span><span class="cn">Inf</span>, <span class="at">label =</span> <span class="st">&quot;Error bars are +/- 1xSD&quot;</span>, </span>
<span id="cb176-15"><a href="gage-rr.html#cb176-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">colour =</span> <span class="st">&quot;grey30&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>, </span>
<span id="cb176-16"><a href="gage-rr.html#cb176-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">fontface =</span> <span class="st">&quot;italic&quot;</span>) <span class="sc">+</span></span>
<span id="cb176-17"><a href="gage-rr.html#cb176-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb176-18"><a href="gage-rr.html#cb176-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Pod volume method validation&quot;</span>,</span>
<span id="cb176-19"><a href="gage-rr.html#cb176-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Interaction plot - L Pod x Operator&quot;</span>,</span>
<span id="cb176-20"><a href="gage-rr.html#cb176-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb176-21"><a href="gage-rr.html#cb176-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Volume [mm]&quot;</span>,</span>
<span id="cb176-22"><a href="gage-rr.html#cb176-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">&quot;Data source: QA Lab&quot;</span>)</span></code></pre></div>
<p><img src="IndustRialds_files/figure-html/unnamed-chunk-61-1.png" width="80%" /></p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="gage-rr.html#cb177-1" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> repea_repro_L <span class="sc">%&gt;%</span></span>
<span id="cb177-2"><a href="gage-rr.html#cb177-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(pod, operator) <span class="sc">%&gt;%</span></span>
<span id="cb177-3"><a href="gage-rr.html#cb177-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">vol_mean =</span> <span class="fu">mean</span>(volume_mm3), <span class="at">vol_sd =</span> <span class="fu">sd</span>(volume_mm3))</span></code></pre></div>
</div>
</div>
<div id="concern-negative-components-of-variation" class="section level2">
<h2>Concern: negative Components of Variation</h2>
<p>Two important limitations exist in the current approach:</p>
<ol style="list-style-type: decimal">
<li>when the operators reproducibility is negative it is converted to zero.</li>
</ol>
<p><span class="citation">(<a href="references-1.html#ref-Montgomery2012" role="doc-biblioref">Montgomery 2012</a>)</span> in page 557 adresses this case in the following way:</p>
<p><em>Notice that the estimate of one of the variance components,is negative. This is certainly not reasonable because by definition variances are nonnegative. Unfortunately, negative estimates of variance components can result when we use the analysis of variance method of estimation (this is considered one of its drawbacks). We can deal with this negative result in a variety of ways:</em></p>
<p><em>1) one possibility is to assume that the negative estimate means that the variance component is really zero and just set it to zero, leaving the other nonnegative estimates unchanged.</em></p>
<p><em>2) Another approach is to estimate the variance components with a method that assures nonnegative estimates (this can be done with the maximum likelihood approach).</em></p>
<p><em>3) Finally, we could note that the P-value for the interaction term … is very large, take this as evidence that really is zero and that there is no interaction effect, and then fit a reduced model of the form that does not include the interaction term. This is a relatively easy approach and one that often works nearly as well as more sophisticated methods.</em></p>
<p>This final approach is also what the SixSigma package creators have foreseen and if we leave the argument alphaLim empty the non significant terms will be suppressed from the model, the Anova recalculated and the remaining tables updated accordingly:</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="gage-rr.html#cb178-1" aria-hidden="true" tabindex="-1"></a>repea_repro_L_rr <span class="ot">&lt;-</span> <span class="fu">ss.rr</span>(</span>
<span id="cb178-2"><a href="gage-rr.html#cb178-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> repea_repro_L, </span>
<span id="cb178-3"><a href="gage-rr.html#cb178-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">var =</span> volume_mm3, </span>
<span id="cb178-4"><a href="gage-rr.html#cb178-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">part =</span> pod, </span>
<span id="cb178-5"><a href="gage-rr.html#cb178-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">appr =</span> operator, </span>
<span id="cb178-6"><a href="gage-rr.html#cb178-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># errorTerm = </span></span>
<span id="cb178-7"><a href="gage-rr.html#cb178-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">&quot;Keyence KEYENCE VR-5200</span><span class="sc">\n</span><span class="st">r&amp;R for Pod Volume&quot;</span>,</span>
<span id="cb178-8"><a href="gage-rr.html#cb178-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">sub =</span> <span class="st">&quot;Pod L&quot;</span>,</span>
<span id="cb178-9"><a href="gage-rr.html#cb178-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">lsl =</span> <span class="dv">17075</span>,</span>
<span id="cb178-10"><a href="gage-rr.html#cb178-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">usl =</span> <span class="dv">18025</span></span>
<span id="cb178-11"><a href="gage-rr.html#cb178-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Complete model (with interaction):
## 
##                Df Sum Sq Mean Sq F value   Pr(&gt;F)
## pod             4 170707   42677 304.181 9.06e-09
## operator        2   1313     657   4.680   0.0451
## pod:operator    8   1122     140   0.892   0.5237
## Repeatability 210  33016     157                 
## Total         224 206158                         
## 
## alpha for removing interaction: 0.05 
## 
## 
## Reduced model (without interaction):
## 
##                Df Sum Sq Mean Sq F value Pr(&gt;F)
## pod             4 170707   42677 272.526 &lt;2e-16
## operator        2   1313     657   4.193 0.0163
## Repeatability 218  34138     157               
## Total         224 206158                       
## 
## Gage R&amp;R
## 
##                       VarComp %Contrib
## Total Gage R&amp;R     163.262567    14.73
##   Repeatability    156.596490    14.13
##   Reproducibility    6.666077     0.60
##     operator         6.666077     0.60
## Part-To-Part       944.889591    85.27
## Total Variation   1108.152158   100.00
## 
##                       VarComp    StdDev  StudyVar %StudyVar %Tolerance
## Total Gage R&amp;R     163.262567 12.777424  76.66454     38.38       8.07
##   Repeatability    156.596490 12.513852  75.08311     37.59       7.90
##   Reproducibility    6.666077  2.581875  15.49125      7.76       1.63
##     operator         6.666077  2.581875  15.49125      7.76       1.63
## Part-To-Part       944.889591 30.739056 184.43434     92.34      19.41
## Total Variation   1108.152158 33.288919 199.73352    100.00      21.02
## 
## Number of Distinct Categories = 3</code></pre>
<p><img src="IndustRialds_files/figure-html/unnamed-chunk-63-1.png" width="80%" /></p>
<p>In our case when comparing the total gage r&amp;R with and without the interaction we see it changing from 38.46% to 38.38%.</p>
</div>
<div id="concern-analysis-beyond-two-factors" class="section level2">
<h2>Concern: analysis beyond two factors</h2>
<ol start="2" style="list-style-type: decimal">
<li>The ss.rr function only accepts 2 factors so it is not possible to obtain all the tables and plots with for example the day as a factor.
This significantly limits the calculation of the total uncertainty for some measurement methods. Next steps in our study will be to prepare an R function to deal with more than 2 factors.</li>
</ol>
</div>
<div id="other-concerns" class="section level2">
<h2>Other concerns</h2>
<p>The randomization is an important aspect that was not mentionned here but that needs to be taken in consideration in the data collection.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="MSA.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="conclusions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
