<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4.2 Single factor designs | industRial data science</title>
  <meta name="description" content="4.2 Single factor designs | industRial data science" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="4.2 Single factor designs | industRial data science" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4.2 Single factor designs | industRial data science" />
  
  
  

<meta name="author" content="João Ramalho" />


<meta name="date" content="2021-01-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="simple-comparative-experiments.html"/>
<link rel="next" href="two-factors-anova-fixed-effects-model.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">industRial data science</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="part"><span><b>I FRAMEWORK</b></span></li>
<li class="chapter" data-level="1" data-path="six-sigma.html"><a href="six-sigma.html"><i class="fa fa-check"></i><b>1</b> Six Sigma</a>
<ul>
<li class="chapter" data-level="1.1" data-path="cause-and-effect-diagrams.html"><a href="cause-and-effect-diagrams.html"><i class="fa fa-check"></i><b>1.1</b> Cause and Effect diagrams</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistics.html"><a href="statistics.html"><i class="fa fa-check"></i><b>2</b> Statistics</a></li>
<li class="chapter" data-level="3" data-path="r-and-data-science.html"><a href="r-and-data-science.html"><i class="fa fa-check"></i><b>3</b> R and Data Science</a>
<ul>
<li class="chapter" data-level="3.1" data-path="why-r.html"><a href="why-r.html"><i class="fa fa-check"></i><b>3.1</b> Why R</a></li>
</ul></li>
<li class="part"><span><b>II CASE STUDIES</b></span></li>
<li class="chapter" data-level="4" data-path="DOE.html"><a href="DOE.html"><i class="fa fa-check"></i><b>4</b> DOE - Design of Experiments</a>
<ul>
<li class="chapter" data-level="4.1" data-path="simple-comparative-experiments.html"><a href="simple-comparative-experiments.html"><i class="fa fa-check"></i><b>4.1</b> Simple comparative experiments</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="simple-comparative-experiments.html"><a href="simple-comparative-experiments.html#the-cement-example"><i class="fa fa-check"></i><b>4.1.1</b> The Cement example</a></li>
<li class="chapter" data-level="4.1.2" data-path="simple-comparative-experiments.html"><a href="simple-comparative-experiments.html#homogeneity-of-variances-test-levene-test"><i class="fa fa-check"></i><b>4.1.2</b> Homogeneity of variances test (Levene Test)</a></li>
<li class="chapter" data-level="4.1.3" data-path="simple-comparative-experiments.html"><a href="simple-comparative-experiments.html#sample-size-calculation"><i class="fa fa-check"></i><b>4.1.3</b> Sample size calculation</a></li>
<li class="chapter" data-level="4.1.4" data-path="simple-comparative-experiments.html"><a href="simple-comparative-experiments.html#t-test-paired"><i class="fa fa-check"></i><b>4.1.4</b> t-test paired</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="single-factor-designs.html"><a href="single-factor-designs.html"><i class="fa fa-check"></i><b>4.2</b> Single factor designs</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="single-factor-designs.html"><a href="single-factor-designs.html#plasma-etching-example"><i class="fa fa-check"></i><b>4.2.1</b> Plasma etching example</a></li>
<li class="chapter" data-level="4.2.2" data-path="single-factor-designs.html"><a href="single-factor-designs.html#analysis-of-variance"><i class="fa fa-check"></i><b>4.2.2</b> Analysis of variance</a></li>
<li class="chapter" data-level="4.2.3" data-path="single-factor-designs.html"><a href="single-factor-designs.html#single-factor-anova-fixed-effects-model"><i class="fa fa-check"></i><b>4.2.3</b> Single factor Anova, fixed effects model</a></li>
<li class="chapter" data-level="4.2.4" data-path="single-factor-designs.html"><a href="single-factor-designs.html#model-adequacy-check"><i class="fa fa-check"></i><b>4.2.4</b> Model adequacy check</a></li>
<li class="chapter" data-level="4.2.5" data-path="single-factor-designs.html"><a href="single-factor-designs.html#residuals-normality-check-outliers"><i class="fa fa-check"></i><b>4.2.5</b> Residuals normality check &amp; outliers</a></li>
<li class="chapter" data-level="4.2.6" data-path="single-factor-designs.html"><a href="single-factor-designs.html#plot-of-residuals-in-time-sequence"><i class="fa fa-check"></i><b>4.2.6</b> Plot of residuals in time sequence</a></li>
<li class="chapter" data-level="4.2.7" data-path="single-factor-designs.html"><a href="single-factor-designs.html#plot-of-residuals-versus-fitted-values"><i class="fa fa-check"></i><b>4.2.7</b> Plot of residuals versus fitted values</a></li>
<li class="chapter" data-level="4.2.8" data-path="single-factor-designs.html"><a href="single-factor-designs.html#equality-of-variances-test-barletts-test"><i class="fa fa-check"></i><b>4.2.8</b> Equality of variances test (Barlett’s test)</a></li>
<li class="chapter" data-level="4.2.9" data-path="single-factor-designs.html"><a href="single-factor-designs.html#tuckeys-pairwise-comparison-test"><i class="fa fa-check"></i><b>4.2.9</b> Tuckey’s pairwise comparison test</a></li>
<li class="chapter" data-level="4.2.10" data-path="single-factor-designs.html"><a href="single-factor-designs.html#fishers-lsd---pairwise-comparison-test"><i class="fa fa-check"></i><b>4.2.10</b> Fisher’s LSD - pairwise comparison test</a></li>
<li class="chapter" data-level="4.2.11" data-path="single-factor-designs.html"><a href="single-factor-designs.html#practical-interpretation-of-results"><i class="fa fa-check"></i><b>4.2.11</b> Practical interpretation of results</a></li>
<li class="chapter" data-level="4.2.12" data-path="single-factor-designs.html"><a href="single-factor-designs.html#linear-model"><i class="fa fa-check"></i><b>4.2.12</b> Linear model</a></li>
<li class="chapter" data-level="4.2.13" data-path="single-factor-designs.html"><a href="single-factor-designs.html#linear-model-plot"><i class="fa fa-check"></i><b>4.2.13</b> Linear model plot</a></li>
<li class="chapter" data-level="4.2.14" data-path="single-factor-designs.html"><a href="single-factor-designs.html#predicting-new-values"><i class="fa fa-check"></i><b>4.2.14</b> Predicting new values</a></li>
<li class="chapter" data-level="4.2.15" data-path="single-factor-designs.html"><a href="single-factor-designs.html#r²-coefficient-of-determination"><i class="fa fa-check"></i><b>4.2.15</b> R², coefficient of determination</a></li>
<li class="chapter" data-level="4.2.16" data-path="single-factor-designs.html"><a href="single-factor-designs.html#sample-size-calculation-1"><i class="fa fa-check"></i><b>4.2.16</b> Sample size calculation</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="two-factors-anova-fixed-effects-model.html"><a href="two-factors-anova-fixed-effects-model.html"><i class="fa fa-check"></i><b>4.3</b> two-factors ANOVA, fixed effects model</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="two-factors-anova-fixed-effects-model.html"><a href="two-factors-anova-fixed-effects-model.html#battery-life-example"><i class="fa fa-check"></i><b>4.3.1</b> Battery life example</a></li>
<li class="chapter" data-level="4.3.2" data-path="two-factors-anova-fixed-effects-model.html"><a href="two-factors-anova-fixed-effects-model.html#analysis-of-variance-1"><i class="fa fa-check"></i><b>4.3.2</b> Analysis of variance</a></li>
<li class="chapter" data-level="4.3.3" data-path="two-factors-anova-fixed-effects-model.html"><a href="two-factors-anova-fixed-effects-model.html#doe-and-anova-plots"><i class="fa fa-check"></i><b>4.3.3</b> DoE and Anova plots</a></li>
<li class="chapter" data-level="4.3.4" data-path="two-factors-anova-fixed-effects-model.html"><a href="two-factors-anova-fixed-effects-model.html#r²-coefficient-of-determination-1"><i class="fa fa-check"></i><b>4.3.4</b> R², coefficient of determination</a></li>
<li class="chapter" data-level="4.3.5" data-path="two-factors-anova-fixed-effects-model.html"><a href="two-factors-anova-fixed-effects-model.html#model-adequacy-checking"><i class="fa fa-check"></i><b>4.3.5</b> Model adequacy checking</a></li>
<li class="chapter" data-level="4.3.6" data-path="two-factors-anova-fixed-effects-model.html"><a href="two-factors-anova-fixed-effects-model.html#residuals-normality-check-outliers-1"><i class="fa fa-check"></i><b>4.3.6</b> Residuals normality check &amp; outliers</a></li>
<li class="chapter" data-level="4.3.7" data-path="two-factors-anova-fixed-effects-model.html"><a href="two-factors-anova-fixed-effects-model.html#plot-of-residuals-versus-fitted-values-1"><i class="fa fa-check"></i><b>4.3.7</b> Plot of residuals versus fitted values</a></li>
<li class="chapter" data-level="4.3.8" data-path="two-factors-anova-fixed-effects-model.html"><a href="two-factors-anova-fixed-effects-model.html#sample-size-calculation-2"><i class="fa fa-check"></i><b>4.3.8</b> Sample size calculation</a></li>
<li class="chapter" data-level="4.3.9" data-path="two-factors-anova-fixed-effects-model.html"><a href="two-factors-anova-fixed-effects-model.html#model-with-no-interaction"><i class="fa fa-check"></i><b>4.3.9</b> Model with no interaction</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="general-factorial-design.html"><a href="general-factorial-design.html"><i class="fa fa-check"></i><b>4.4</b> General factorial design</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="general-factorial-design.html"><a href="general-factorial-design.html#soft-drink-bottling-example"><i class="fa fa-check"></i><b>4.4.1</b> Soft Drink bottling example</a></li>
<li class="chapter" data-level="4.4.2" data-path="general-factorial-design.html"><a href="general-factorial-design.html#analysis-of-variance-2"><i class="fa fa-check"></i><b>4.4.2</b> Analysis of variance</a></li>
<li class="chapter" data-level="4.4.3" data-path="general-factorial-design.html"><a href="general-factorial-design.html#residuals-analysis"><i class="fa fa-check"></i><b>4.4.3</b> Residuals analysis</a></li>
<li class="chapter" data-level="4.4.4" data-path="general-factorial-design.html"><a href="general-factorial-design.html#doe-plots"><i class="fa fa-check"></i><b>4.4.4</b> DoE plots</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="the-2k-factorial-designs.html"><a href="the-2k-factorial-designs.html"><i class="fa fa-check"></i><b>4.5</b> The 2^k factorial designs</a></li>
<li class="chapter" data-level="4.6" data-path="the-22-factorial-design.html"><a href="the-22-factorial-design.html"><i class="fa fa-check"></i><b>4.6</b> The 2^2 Factorial Design</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="the-22-factorial-design.html"><a href="the-22-factorial-design.html#the-chemical-process-example"><i class="fa fa-check"></i><b>4.6.1</b> The Chemical Process example</a></li>
<li class="chapter" data-level="4.6.2" data-path="the-22-factorial-design.html"><a href="the-22-factorial-design.html#anova"><i class="fa fa-check"></i><b>4.6.2</b> Anova</a></li>
<li class="chapter" data-level="4.6.3" data-path="the-22-factorial-design.html"><a href="the-22-factorial-design.html#regression-model-prediction"><i class="fa fa-check"></i><b>4.6.3</b> Regression model / Prediction</a></li>
<li class="chapter" data-level="4.6.4" data-path="the-22-factorial-design.html"><a href="the-22-factorial-design.html#response-surface"><i class="fa fa-check"></i><b>4.6.4</b> Response surface</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="the-23-factorial-design.html"><a href="the-23-factorial-design.html"><i class="fa fa-check"></i><b>4.7</b> The 2^3 Factorial Design</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="the-23-factorial-design.html"><a href="the-23-factorial-design.html#the-plasma-etching-example"><i class="fa fa-check"></i><b>4.7.1</b> The plasma etching example</a></li>
<li class="chapter" data-level="4.7.2" data-path="the-23-factorial-design.html"><a href="the-23-factorial-design.html#anova-1"><i class="fa fa-check"></i><b>4.7.2</b> Anova</a></li>
<li class="chapter" data-level="4.7.3" data-path="the-23-factorial-design.html"><a href="the-23-factorial-design.html#regression-model-prediction-1"><i class="fa fa-check"></i><b>4.7.3</b> Regression model / Prediction</a></li>
<li class="chapter" data-level="4.7.4" data-path="the-23-factorial-design.html"><a href="the-23-factorial-design.html#reduced-model"><i class="fa fa-check"></i><b>4.7.4</b> Reduced model</a></li>
<li class="chapter" data-level="4.7.5" data-path="the-23-factorial-design.html"><a href="the-23-factorial-design.html#doe-plots-1"><i class="fa fa-check"></i><b>4.7.5</b> DoE plots</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="the-general-2k-design.html"><a href="the-general-2k-design.html"><i class="fa fa-check"></i><b>4.8</b> The general 2^k design</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="the-general-2k-design.html"><a href="the-general-2k-design.html#calculating-the-number-combinations"><i class="fa fa-check"></i><b>4.8.1</b> Calculating the number combinations</a></li>
<li class="chapter" data-level="4.8.2" data-path="the-general-2k-design.html"><a href="the-general-2k-design.html#relationship-coded-vs-natural-variables"><i class="fa fa-check"></i><b>4.8.2</b> Relationship coded vs natural variables</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="single-replicate-2k-design.html"><a href="single-replicate-2k-design.html"><i class="fa fa-check"></i><b>4.9</b> Single replicate 2^k design</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="single-replicate-2k-design.html"><a href="single-replicate-2k-design.html#the-filtration-example"><i class="fa fa-check"></i><b>4.9.1</b> The Filtration example</a></li>
<li class="chapter" data-level="4.9.2" data-path="single-replicate-2k-design.html"><a href="single-replicate-2k-design.html#anova-2"><i class="fa fa-check"></i><b>4.9.2</b> Anova</a></li>
<li class="chapter" data-level="4.9.3" data-path="single-replicate-2k-design.html"><a href="single-replicate-2k-design.html#linear-regression---plot-of-effects"><i class="fa fa-check"></i><b>4.9.3</b> Linear regression - Plot of effects</a></li>
<li class="chapter" data-level="4.9.4" data-path="single-replicate-2k-design.html"><a href="single-replicate-2k-design.html#doe-plots-2"><i class="fa fa-check"></i><b>4.9.4</b> DoE plots</a></li>
<li class="chapter" data-level="4.9.5" data-path="single-replicate-2k-design.html"><a href="single-replicate-2k-design.html#anova-reduced-model-significant-effects-only"><i class="fa fa-check"></i><b>4.9.5</b> Anova reduced model (significant effects only)</a></li>
<li class="chapter" data-level="4.9.6" data-path="single-replicate-2k-design.html"><a href="single-replicate-2k-design.html#linear-regression---reduced-model"><i class="fa fa-check"></i><b>4.9.6</b> Linear regression - reduced model</a></li>
<li class="chapter" data-level="4.9.7" data-path="single-replicate-2k-design.html"><a href="single-replicate-2k-design.html#residuals-normality-check"><i class="fa fa-check"></i><b>4.9.7</b> Residuals normality check</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="two-level-fractional-factorial-designs.html"><a href="two-level-fractional-factorial-designs.html"><i class="fa fa-check"></i><b>4.10</b> Two level fractional factorial designs</a>
<ul>
<li class="chapter" data-level="4.10.1" data-path="two-level-fractional-factorial-designs.html"><a href="two-level-fractional-factorial-designs.html#the-one-half-fraction-of-th-2k-design"><i class="fa fa-check"></i><b>4.10.1</b> The One-Half Fraction of th 2k Design</a></li>
<li class="chapter" data-level="4.10.2" data-path="two-level-fractional-factorial-designs.html"><a href="two-level-fractional-factorial-designs.html#the-filtration-example-modified"><i class="fa fa-check"></i><b>4.10.2</b> The filtration example (modified)</a></li>
<li class="chapter" data-level="4.10.3" data-path="two-level-fractional-factorial-designs.html"><a href="two-level-fractional-factorial-designs.html#anova-3"><i class="fa fa-check"></i><b>4.10.3</b> Anova</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html"><i class="fa fa-check"></i><b>4.11</b> Analysis of Covariance</a>
<ul>
<li class="chapter" data-level="4.11.1" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#approach"><i class="fa fa-check"></i><b>4.11.1</b> Approach</a></li>
<li class="chapter" data-level="4.11.2" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#case-study"><i class="fa fa-check"></i><b>4.11.2</b> Case study</a></li>
<li class="chapter" data-level="4.11.3" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#ancova"><i class="fa fa-check"></i><b>4.11.3</b> Ancova</a></li>
<li class="chapter" data-level="4.11.4" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#comparison-with-anova"><i class="fa fa-check"></i><b>4.11.4</b> Comparison with anova</a></li>
<li class="chapter" data-level="4.11.5" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html#potential-applications"><i class="fa fa-check"></i><b>4.11.5</b> Potential applications</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="MSA.html"><a href="MSA.html"><i class="fa fa-check"></i><b>5</b> MSA - Measurement System Analysis</a></li>
<li class="chapter" data-level="6" data-path="SPC.html"><a href="SPC.html"><i class="fa fa-check"></i><b>6</b> SPC - Statistical Process Control</a>
<ul>
<li class="chapter" data-level="6.1" data-path="case-study-1.html"><a href="case-study-1.html"><i class="fa fa-check"></i><b>6.1</b> Case study</a></li>
<li class="chapter" data-level="6.2" data-path="xbar-and-r-charts.html"><a href="xbar-and-r-charts.html"><i class="fa fa-check"></i><b>6.2</b> xbar and R charts</a></li>
<li class="chapter" data-level="6.3" data-path="warnings-and-specification-limits.html"><a href="warnings-and-specification-limits.html"><i class="fa fa-check"></i><b>6.3</b> Warnings and specification limits</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="Cpk.html"><a href="Cpk.html"><i class="fa fa-check"></i><b>7</b> CPK - Process Capability Analysis</a>
<ul>
<li class="chapter" data-level="7.1" data-path="case-study-2.html"><a href="case-study-2.html"><i class="fa fa-check"></i><b>7.1</b> Case study</a></li>
<li class="chapter" data-level="7.2" data-path="process-capability-chart.html"><a href="process-capability-chart.html"><i class="fa fa-check"></i><b>7.2</b> Process Capability chart</a></li>
</ul></li>
<li class="part"><span><b>III TOOLBOX</b></span></li>
<li class="chapter" data-level="8" data-path="Rpck.html"><a href="Rpck.html"><i class="fa fa-check"></i><b>8</b> R Packages</a>
<ul>
<li class="chapter" data-level="8.1" data-path="six-sigma-1.html"><a href="six-sigma-1.html"><i class="fa fa-check"></i><b>8.1</b> six sigma</a></li>
<li class="chapter" data-level="8.2" data-path="ggspc.html"><a href="ggspc.html"><i class="fa fa-check"></i><b>8.2</b> ggspc</a></li>
<li class="chapter" data-level="8.3" data-path="qcc.html"><a href="qcc.html"><i class="fa fa-check"></i><b>8.3</b> qcc</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="datasets.html"><a href="datasets.html"><i class="fa fa-check"></i><b>9</b> Datasets</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">indust<b style='color:#079DFE'>R</b>ial data science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="single-factor-designs" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Single factor designs</h2>
<p>CHAPTER 3 <span class="citation">(<a href="references.html#ref-Montgomery2012" role="doc-biblioref">Montgomery 2012</a>)</span></p>
<p>Randomization of the test sequence is a required practice, not only because of operator effects but also due to other potentially unknown effects like machine warm up.</p>
<div id="plasma-etching-example" class="section level3" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Plasma etching example</h3>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="single-factor-designs.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Direct copy of the example from the book:</span></span>
<span id="cb15-2"><a href="single-factor-designs.html#cb15-2" aria-hidden="true" tabindex="-1"></a>plasma <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">sep =</span> <span class="st">&quot;;&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>,</span>
<span id="cb15-3"><a href="single-factor-designs.html#cb15-3" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">paste0</span>(working_folder, <span class="st">&quot;3-1 plasma etching.csv&quot;</span>))</span>
<span id="cb15-4"><a href="single-factor-designs.html#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="single-factor-designs.html#cb15-5" aria-hidden="true" tabindex="-1"></a>plasma <span class="ot">&lt;-</span> <span class="fu">mutate</span>(plasma, </span>
<span id="cb15-6"><a href="single-factor-designs.html#cb15-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">totals =</span>  (X1 <span class="sc">+</span> X2 <span class="sc">+</span> X3 <span class="sc">+</span> X4 <span class="sc">+</span> X5 ),</span>
<span id="cb15-7"><a href="single-factor-designs.html#cb15-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">averages =</span> totals <span class="sc">/</span> <span class="dv">5</span>)</span>
<span id="cb15-8"><a href="single-factor-designs.html#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="single-factor-designs.html#cb15-9" aria-hidden="true" tabindex="-1"></a>overall_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(plasma<span class="sc">$</span>averages)</span>
<span id="cb15-10"><a href="single-factor-designs.html#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="single-factor-designs.html#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Converting into a narrow table with a factor for utilisation with ggplot2</span></span>
<span id="cb15-12"><a href="single-factor-designs.html#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="co"># syntax: gather(data, </span></span>
<span id="cb15-13"><a href="single-factor-designs.html#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="co">#               name of the new key column (where the columns names go to), </span></span>
<span id="cb15-14"><a href="single-factor-designs.html#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="co">#               name of the new value column (where the values go), </span></span>
<span id="cb15-15"><a href="single-factor-designs.html#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="co">#               name of the columns to be gathered)</span></span>
<span id="cb15-16"><a href="single-factor-designs.html#cb15-16" aria-hidden="true" tabindex="-1"></a>plasma_narrow <span class="ot">&lt;-</span> plasma <span class="sc">%&gt;%</span></span>
<span id="cb15-17"><a href="single-factor-designs.html#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(power, X1, X2, X3, X4, X5) <span class="sc">%&gt;%</span></span>
<span id="cb15-18"><a href="single-factor-designs.html#cb15-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(observation, etch_rate, X1, X2, X3, X4, X5)</span>
<span id="cb15-19"><a href="single-factor-designs.html#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="co"># plasma_narrow$power &lt;- as.factor(plasma_narrow$power)</span></span></code></pre></div>
<p>DoE Plots</p>
<p>Typically the DoE results are presented with a box plot and a scatter diagram as below:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="single-factor-designs.html#cb16-1" aria-hidden="true" tabindex="-1"></a>plasma_narrow_factor <span class="ot">&lt;-</span> plasma_narrow</span>
<span id="cb16-2"><a href="single-factor-designs.html#cb16-2" aria-hidden="true" tabindex="-1"></a>plasma_narrow_factor<span class="sc">$</span>power <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(plasma_narrow<span class="sc">$</span>power)</span></code></pre></div>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="single-factor-designs.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot</span></span>
<span id="cb17-2"><a href="single-factor-designs.html#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plasma_narrow_factor, <span class="fu">aes</span>(<span class="at">x =</span> power, <span class="at">y =</span> etch_rate)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="single-factor-designs.html#cb17-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="IndustRialds_files/figure-html/plasma-fig-1.png" width="80%" /></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="single-factor-designs.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter diagram</span></span>
<span id="cb18-2"><a href="single-factor-designs.html#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plasma_narrow_factor, <span class="fu">aes</span>(<span class="at">x =</span> power, <span class="at">y =</span> etch_rate)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="single-factor-designs.html#cb18-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="IndustRialds_files/figure-html/plasma-fig-2.png" width="80%" /></p>
</div>
<div id="analysis-of-variance" class="section level3" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Analysis of variance</h3>
<p>3.2.</p>
<p>According to Montgomery the Anova or analysis of variance is probably the most useful technique in the field of statistical inference.</p>
<p>1 factor with severals levels + 1 continuous dependent variable
Similar to the t-test but extended - this test allows to compare the means between several levels of treatement for a continuous response variable (the t test is only 2 levels at a time, performing all pair wise t-tests would also not be a solution because its a lot of effort and would increase the type I error)</p>
<p>ANOVA principle: the total variability in the data, as measured by the total corrected sum of squares, can be partitioned into a sum of squares of the differences between the treatment averages and the grand average plus a sum of squares of the differences of observations within treatments from the treatment average</p>
</div>
<div id="single-factor-anova-fixed-effects-model" class="section level3" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> Single factor Anova, fixed effects model</h3>
<p>3.3.
Anova on plasma etching example (ANOVA, single factor, fixed effects model)</p>
<p>In R the anova is built by passing the linear model to the anova or aov functions.
The output of the anova function is just the anova table as shown here for this first example. The output of the aov function is a list.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="single-factor-designs.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First approach: anova function - create a linear model (treatment has to be a factor)</span></span>
<span id="cb19-2"><a href="single-factor-designs.html#cb19-2" aria-hidden="true" tabindex="-1"></a>plasma_lm_factor <span class="ot">&lt;-</span> <span class="fu">lm</span>(etch_rate <span class="sc">~</span> power, <span class="at">data =</span> plasma_narrow_factor)</span>
<span id="cb19-3"><a href="single-factor-designs.html#cb19-3" aria-hidden="true" tabindex="-1"></a>plasma_anova <span class="ot">&lt;-</span> <span class="fu">anova</span>(plasma_lm_factor)</span>
<span id="cb19-4"><a href="single-factor-designs.html#cb19-4" aria-hidden="true" tabindex="-1"></a>plasma_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(plasma_lm_factor)</span>
<span id="cb19-5"><a href="single-factor-designs.html#cb19-5" aria-hidden="true" tabindex="-1"></a>plasma_anova</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: etch_rate
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## power      3  66871 22290.2  66.797 2.883e-09 ***
## Residuals 16   5339   333.7                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="single-factor-designs.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(plasma_aov)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## power        3  66871   22290    66.8 2.88e-09 ***
## Residuals   16   5339     334                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Note: book example correctly reproduced.</p>
<p>Note that the RF power or between-treatment mean square (22,290.18) is many times larger than the within-treatment or error mean square (333.70). This indicates that it is unlikely that the treatment means are equal.
Also p &lt; 0.05 thus we can reject the null hypothesis and conclude that the means are significantly different.</p>
<p>Anova on plasma etching, modification of the example to achieve a p &gt; 0.05:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="single-factor-designs.html#cb23-1" aria-hidden="true" tabindex="-1"></a>plasma2 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">sep =</span> <span class="st">&quot;;&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>,</span>
<span id="cb23-2"><a href="single-factor-designs.html#cb23-2" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">paste0</span>(working_folder, <span class="st">&quot;3-1 plasma etching 2.csv&quot;</span>))</span>
<span id="cb23-3"><a href="single-factor-designs.html#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="single-factor-designs.html#cb23-4" aria-hidden="true" tabindex="-1"></a>plasma2_narrow <span class="ot">&lt;-</span> <span class="fu">gather</span>(plasma2, observation, etch_rate, X1, X2, X3, X4, X5)</span>
<span id="cb23-5"><a href="single-factor-designs.html#cb23-5" aria-hidden="true" tabindex="-1"></a>plasma2_narrow_factor <span class="ot">&lt;-</span> plasma2_narrow</span>
<span id="cb23-6"><a href="single-factor-designs.html#cb23-6" aria-hidden="true" tabindex="-1"></a>plasma2_narrow_factor<span class="sc">$</span>power <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(plasma2_narrow_factor<span class="sc">$</span>power)</span>
<span id="cb23-7"><a href="single-factor-designs.html#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="single-factor-designs.html#cb23-8" aria-hidden="true" tabindex="-1"></a>plasma2_lm_factor <span class="ot">&lt;-</span> <span class="fu">lm</span>(etch_rate <span class="sc">~</span> power, <span class="at">data =</span> plasma2_narrow_factor)</span>
<span id="cb23-9"><a href="single-factor-designs.html#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(plasma2_lm_factor)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: etch_rate
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## power      3   1476   492.0  1.2015  0.341
## Residuals 16   6552   409.5</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="single-factor-designs.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plasma2_narrow_factor, <span class="fu">aes</span>(<span class="at">x =</span> power, <span class="at">y =</span> etch_rate)) <span class="sc">+</span></span>
<span id="cb25-2"><a href="single-factor-designs.html#cb25-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="IndustRialds_files/figure-html/plasma2_box-fig-1.png" width="80%" /></p>
<p>P &gt; 0.05 - there is no significant difference between the means</p>
</div>
<div id="model-adequacy-check" class="section level3" number="4.2.4">
<h3><span class="header-section-number">4.2.4</span> Model adequacy check</h3>
<p>3.4.</p>
</div>
<div id="residuals-normality-check-outliers" class="section level3" number="4.2.5">
<h3><span class="header-section-number">4.2.5</span> Residuals normality check &amp; outliers</h3>
<p>Anova fixed effects assumes that:
- errors are normally distributed and are independent</p>
<p>Q-Q plot + Shapiro-Wilk test</p>
<p>As the number of residuals is too small we’re not checking the normality via the histogram but rather with a a Q-Q plot.
The plot suggests normal distribution. The verification can be completed by a test. For populations &lt; 50 use the shapiro-wilk normality test.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="single-factor-designs.html#cb26-1" aria-hidden="true" tabindex="-1"></a>plasma_residuals <span class="ot">&lt;-</span> plasma_aov<span class="sc">$</span>residuals</span>
<span id="cb26-2"><a href="single-factor-designs.html#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(plasma_residuals, <span class="at">datax =</span> <span class="cn">TRUE</span>); <span class="fu">qqline</span>(plasma_residuals, <span class="at">datax =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="IndustRialds_files/figure-html/plasma_res-fig-1.png" width="80%" /></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="single-factor-designs.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(plasma_residuals)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  plasma_residuals
## W = 0.93752, p-value = 0.2152</code></pre>
<p>p &gt; 0.05 indicates that the residuals do not differ significantly from a normally distributed population.</p>
<p>Standardized residuals graph</p>
<p>A second graph shows that the standardised residuals are normally distributed (explanation in a later chunk).
This specific Standardize residuals graph also help detecting outliers in the residuals (any residual &gt; 3 standard deviations is a potential outlier).</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="single-factor-designs.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plasma_aov, <span class="at">which =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="IndustRialds_files/figure-html/plasma_stdres-fig-1.png" width="80%" /></p>
</div>
<div id="plot-of-residuals-in-time-sequence" class="section level3" number="4.2.6">
<h3><span class="header-section-number">4.2.6</span> Plot of residuals in time sequence</h3>
<p>A tendency to have runs of positive of negative results indicates that the independency assumption does not hold.</p>
<p>Such plot needs that the order of data collection is available in the dataframe. In the example below this is NOT the case as the residuals from the model are sequenced as they appear in the <em>plasma</em> dataframe.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="single-factor-designs.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plasma_residuals)</span></code></pre></div>
<p><img src="IndustRialds_files/figure-html/plasma_seqres-fig-1.png" width="80%" /></p>
</div>
<div id="plot-of-residuals-versus-fitted-values" class="section level3" number="4.2.7">
<h3><span class="header-section-number">4.2.7</span> Plot of residuals versus fitted values</h3>
<p>If the model is correct and the assumptions hold, the residuals should be structureless. This plot should not reveal any obvious pattern.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="single-factor-designs.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plasma_aov, <span class="at">which =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="IndustRialds_files/figure-html/plasma_fitres-fig-1.png" width="80%" /></p>
</div>
<div id="equality-of-variances-test-barletts-test" class="section level3" number="4.2.8">
<h3><span class="header-section-number">4.2.8</span> Equality of variances test (Barlett’s test)</h3>
<p>In the plasma etch experiment, the normality assumption is not in question, so we can apply Bartlett’s test to the etch
rate data.</p>
<p>(Bartlett’s test is very sensitive to the normality assumption. Consequently, when the validity of this assumption is doubtful, Bartlett’s test should not be used. In this case use the Modified Levene test).</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="single-factor-designs.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(etch_rate <span class="sc">~</span> power, <span class="at">data =</span> plasma_narrow)</span></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  etch_rate by power
## Bartlett&#39;s K-squared = 0.43349, df = 3, p-value = 0.9332</code></pre>
<p>The P-value is P = 0.934, so we cannot reject the null hypothesis. There is no evidence to counter the claim that all five variances are the same. This is the same conclusion reached by analyzing the plot of residuals versus fitted values.</p>
</div>
<div id="tuckeys-pairwise-comparison-test" class="section level3" number="4.2.9">
<h3><span class="header-section-number">4.2.9</span> Tuckey’s pairwise comparison test</h3>
<p>The Anova may indicate that the treament means differ but it won’t indicate which ones. In this case we may want to compare pairs of means.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="single-factor-designs.html#cb34-1" aria-hidden="true" tabindex="-1"></a>plasma_tukey <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(plasma_aov, <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb34-2"><a href="single-factor-designs.html#cb34-2" aria-hidden="true" tabindex="-1"></a>plasma_tukey</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
##     factor levels have been ordered
## 
## Fit: aov(formula = plasma_lm_factor)
## 
## $power
##          diff        lwr       upr     p adj
## 180-160  36.2   3.145624  69.25438 0.0294279
## 200-160  74.2  41.145624 107.25438 0.0000455
## 220-160 155.8 122.745624 188.85438 0.0000000
## 200-180  38.0   4.945624  71.05438 0.0215995
## 220-180 119.6  86.545624 152.65438 0.0000001
## 220-200  81.6  48.545624 114.65438 0.0000146</code></pre>
<p>The differences reproduce exactly the book example.</p>
<p>My conclusion is that for all differences p &lt; 0.05, thus all differences are significantly different.
Therefore, each power setting results in a mean etch rate that differs from the mean etch rate at any other power setting.</p>
</div>
<div id="fishers-lsd---pairwise-comparison-test" class="section level3" number="4.2.10">
<h3><span class="header-section-number">4.2.10</span> Fisher’s LSD - pairwise comparison test</h3>
<p>Fisher’s Least Significant difference is an alternative to Tuckey’s test.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="single-factor-designs.html#cb36-1" aria-hidden="true" tabindex="-1"></a>plasma_LSD <span class="ot">&lt;-</span> <span class="fu">LSD.test</span>(<span class="at">y =</span> plasma_narrow_factor<span class="sc">$</span>etch_rate,</span>
<span id="cb36-2"><a href="single-factor-designs.html#cb36-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">trt =</span> plasma_narrow_factor<span class="sc">$</span>power,</span>
<span id="cb36-3"><a href="single-factor-designs.html#cb36-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">DFerror =</span> plasma_anova<span class="sc">$</span>Df[<span class="dv">2</span>],  </span>
<span id="cb36-4"><a href="single-factor-designs.html#cb36-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">MSerror =</span> plasma_anova<span class="sc">$</span><span class="st">`</span><span class="at">Mean Sq</span><span class="st">`</span>[<span class="dv">2</span>],</span>
<span id="cb36-5"><a href="single-factor-designs.html#cb36-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">alpha =</span> <span class="fl">0.05</span>)</span>
<span id="cb36-6"><a href="single-factor-designs.html#cb36-6" aria-hidden="true" tabindex="-1"></a>plasma_LSD</span></code></pre></div>
<pre><code>## $statistics
##   MSerror Df   Mean       CV  t.value      LSD
##     333.7 16 617.75 2.957095 2.119905 24.49202
## 
## $parameters
##         test p.ajusted                     name.t ntr alpha
##   Fisher-LSD      none plasma_narrow_factor$power   4  0.05
## 
## $means
##     plasma_narrow_factor$etch_rate      std r      LCL      UCL Min Max Q25 Q50
## 160                          551.2 20.01749 5 533.8815 568.5185 530 575 539 542
## 180                          587.4 16.74216 5 570.0815 604.7185 565 610 579 590
## 200                          625.4 20.52559 5 608.0815 642.7185 600 651 610 629
## 220                          707.0 15.24795 5 689.6815 724.3185 685 725 700 710
##     Q75
## 160 570
## 180 593
## 200 637
## 220 715
## 
## $comparison
## NULL
## 
## $groups
##     plasma_narrow_factor$etch_rate groups
## 220                          707.0      a
## 200                          625.4      b
## 180                          587.4      c
## 160                          551.2      d
## 
## attr(,&quot;class&quot;)
## [1] &quot;group&quot;</code></pre>
<p>Although the LSD value output from the test doesn’t match exactly the book value of 33.09 the conclusion is the same and can be interpreted from the fact that all means are in different groups (different letters).</p>
</div>
<div id="practical-interpretation-of-results" class="section level3" number="4.2.11">
<h3><span class="header-section-number">4.2.11</span> Practical interpretation of results</h3>
<p>3.5</p>
</div>
<div id="linear-model" class="section level3" number="4.2.12">
<h3><span class="header-section-number">4.2.12</span> Linear model</h3>
<p>Here we’re constructing a linear model of the raw data and not a model of the Anova, thus <em>power</em> has to be as integer and not as a factor, unlike in the Anova model.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="single-factor-designs.html#cb38-1" aria-hidden="true" tabindex="-1"></a>plasma_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(etch_rate <span class="sc">~</span> power, <span class="at">data =</span> plasma_narrow)</span>
<span id="cb38-2"><a href="single-factor-designs.html#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(plasma_lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = etch_rate ~ power, data = plasma_narrow)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -43.02 -12.32  -1.21  16.71  33.06 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 137.6200    41.2108   3.339  0.00365 ** 
## power         2.5270     0.2154  11.731 7.26e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.54 on 18 degrees of freedom
## Multiple R-squared:  0.8843, Adjusted R-squared:  0.8779 
## F-statistic: 137.6 on 1 and 18 DF,  p-value: 7.263e-10</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="single-factor-designs.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Just to demonstrate that with a factor we get completely different results:</span></span>
<span id="cb40-2"><a href="single-factor-designs.html#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(plasma_lm_factor)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = etch_rate ~ power, data = plasma_narrow_factor)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -25.4  -13.0    2.8   13.2   25.6 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  551.200      8.169  67.471  &lt; 2e-16 ***
## power180      36.200     11.553   3.133  0.00642 ** 
## power200      74.200     11.553   6.422 8.44e-06 ***
## power220     155.800     11.553  13.485 3.73e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 18.27 on 16 degrees of freedom
## Multiple R-squared:  0.9261, Adjusted R-squared:  0.9122 
## F-statistic:  66.8 on 3 and 16 DF,  p-value: 2.883e-09</code></pre>
<p>Note: book example correctly reproduced (in the first case with power NOT as a factor)</p>
</div>
<div id="linear-model-plot" class="section level3" number="4.2.13">
<h3><span class="header-section-number">4.2.13</span> Linear model plot</h3>
<p>Same thing for the linear model graph, we have to use the raw data with power as integer and not as a factor.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="single-factor-designs.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plasma_narrow, <span class="fu">aes</span>(<span class="at">x =</span> power, <span class="at">y =</span> etch_rate)) <span class="sc">+</span></span>
<span id="cb42-2"><a href="single-factor-designs.html#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb42-3"><a href="single-factor-designs.html#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="IndustRialds_files/figure-html/plasma_narrow-fig-1.png" width="80%" /></p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="single-factor-designs.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Just to demonstrate that ggplot does not take power as a integer</span></span>
<span id="cb43-2"><a href="single-factor-designs.html#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plasma_narrow_factor, <span class="fu">aes</span>(<span class="at">x =</span> power, <span class="at">y =</span> etch_rate)) <span class="sc">+</span></span>
<span id="cb43-3"><a href="single-factor-designs.html#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb43-4"><a href="single-factor-designs.html#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="IndustRialds_files/figure-html/plasma_narrow-fig-2.png" width="80%" /></p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="single-factor-designs.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plasma_narrow, <span class="fu">aes</span>(<span class="at">x =</span> power, <span class="at">y =</span> etch_rate)) <span class="sc">+</span></span>
<span id="cb44-2"><a href="single-factor-designs.html#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb44-3"><a href="single-factor-designs.html#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">2</span>), <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="IndustRialds_files/figure-html/plasma_narrow-fig-3.png" width="80%" /></p>
</div>
<div id="predicting-new-values" class="section level3" number="4.2.14">
<h3><span class="header-section-number">4.2.14</span> Predicting new values</h3>
<p>Here we’re using the model with power as an integer:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="single-factor-designs.html#cb45-1" aria-hidden="true" tabindex="-1"></a>power_new <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">power =</span> <span class="fu">c</span>(<span class="dv">170</span>, <span class="dv">190</span>))</span>
<span id="cb45-2"><a href="single-factor-designs.html#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(plasma_lm, <span class="at">newdata =</span> power_new)</span></code></pre></div>
<pre><code>##      1      2 
## 567.21 617.75</code></pre>
<p>Note: book example correctly reproduced (with power NOT as a factor)</p>
</div>
<div id="r²-coefficient-of-determination" class="section level3" number="4.2.15">
<h3><span class="header-section-number">4.2.15</span> R², coefficient of determination</h3>
<p>The R square can be extracted from the linear model that has been used to build the Anova model. In this case R² = 0.9261 as seen in the book.
(attention: it is important to make <em>power</em> as a factor before creating the linear model otherwise this gives wrong results).
(attention: the other outputs are not related with the Anova model)</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="single-factor-designs.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(plasma_lm_factor)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = etch_rate ~ power, data = plasma_narrow_factor)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -25.4  -13.0    2.8   13.2   25.6 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  551.200      8.169  67.471  &lt; 2e-16 ***
## power180      36.200     11.553   3.133  0.00642 ** 
## power200      74.200     11.553   6.422 8.44e-06 ***
## power220     155.800     11.553  13.485 3.73e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 18.27 on 16 degrees of freedom
## Multiple R-squared:  0.9261, Adjusted R-squared:  0.9122 
## F-statistic:  66.8 on 3 and 16 DF,  p-value: 2.883e-09</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="single-factor-designs.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Just to demonstrate that the lm model without factor gives different and wrong R^2</span></span>
<span id="cb49-2"><a href="single-factor-designs.html#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(plasma_lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = etch_rate ~ power, data = plasma_narrow)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -43.02 -12.32  -1.21  16.71  33.06 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 137.6200    41.2108   3.339  0.00365 ** 
## power         2.5270     0.2154  11.731 7.26e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.54 on 18 degrees of freedom
## Multiple R-squared:  0.8843, Adjusted R-squared:  0.8779 
## F-statistic: 137.6 on 1 and 18 DF,  p-value: 7.263e-10</code></pre>
<p>Note: book example correctly reproduced (for the first case where <em>Power</em> is a factor).</p>
<p>Thus, in the plasma etching experiment, the factor “power” explains about 92.61 percent of the variability in etch rate.</p>
</div>
<div id="sample-size-calculation-1" class="section level3" number="4.2.16">
<h3><span class="header-section-number">4.2.16</span> Sample size calculation</h3>
<p>Refer to “Statistiques faciles avec R,” page 233.
Cohen’s effect size is calculated with the eta squared from the model (intriguing is the same value as the R²…).
In this case with 2 replicates we obtain a power of 90% and an alpha of 1%.
I’ve not managed here to replicate the values from the Montgomery book.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="single-factor-designs.html#cb51-1" aria-hidden="true" tabindex="-1"></a>plasma_eta2 <span class="ot">&lt;-</span> <span class="fu">etaSquared</span>(plasma_aov)[<span class="dv">1</span>]</span>
<span id="cb51-2"><a href="single-factor-designs.html#cb51-2" aria-hidden="true" tabindex="-1"></a>plasma_cohend_aov <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(plasma_eta2 <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> plasma_eta2))</span>
<span id="cb51-3"><a href="single-factor-designs.html#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="single-factor-designs.html#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">pwr.anova.test</span>(<span class="at">k =</span> <span class="dv">4</span>,</span>
<span id="cb51-5"><a href="single-factor-designs.html#cb51-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">n =</span> <span class="dv">2</span>,</span>
<span id="cb51-6"><a href="single-factor-designs.html#cb51-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">f =</span> plasma_cohend_aov,</span>
<span id="cb51-7"><a href="single-factor-designs.html#cb51-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">sig.level =</span> <span class="fl">0.01</span>)</span></code></pre></div>
<pre><code>## 
##      Balanced one-way analysis of variance power calculation 
## 
##               k = 4
##               n = 2
##               f = 3.53899
##       sig.level = 0.01
##           power = 0.9004508
## 
## NOTE: n is number in each group</code></pre>
<p>Here I have not yet managed to reproduce the book example. See the example in chapter 5 where this has been successfull thus working as a better approach for the future.</p>
<p>Multiple factor designs</p>
<p>CHAPTER 5 <span class="citation">(<a href="references.html#ref-Montgomery2012" role="doc-biblioref">Montgomery 2012</a>)</span></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="simple-comparative-experiments.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="two-factors-anova-fixed-effects-model.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": false
}
});
});
</script>

</body>

</html>
