<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Statistics | industRial data science</title>
  <meta name="description" content="Statistics | industRial data science" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Statistics | industRial data science" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Statistics | industRial data science" />
  
  
  

<meta name="author" content="João Ramalho" />


<meta name="date" content="2021-02-22" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="six-sigma.html"/>
<link rel="next" href="DOE.html"/>
<script src="libs/header-attrs-2.5/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">industRial data science</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="part"><span><b>I CASE STUDIES</b></span></li>
<li class="chapter" data-level="" data-path="six-sigma.html"><a href="six-sigma.html"><i class="fa fa-check"></i>Six Sigma</a>
<ul>
<li class="chapter" data-level="" data-path="six-sigma.html"><a href="six-sigma.html#cause-and-effect-diagram"><i class="fa fa-check"></i>Cause and Effect diagram</a></li>
<li class="chapter" data-level="" data-path="six-sigma.html"><a href="six-sigma.html#pareto-chart"><i class="fa fa-check"></i>Pareto chart</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html"><i class="fa fa-check"></i>Statistics</a>
<ul>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#comparing-means"><i class="fa fa-check"></i>Comparing means</a>
<ul>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#t-test-one-sample"><i class="fa fa-check"></i>t-test one sample</a></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#t-test-two-samples"><i class="fa fa-check"></i>t-test two samples</a></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#t-test-two-samples-paired"><i class="fa fa-check"></i>t-test two samples paired</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#comparing-variances"><i class="fa fa-check"></i>Comparing variances</a>
<ul>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#bonetts-test"><i class="fa fa-check"></i>Bonett’s test</a></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#levene-test"><i class="fa fa-check"></i>Levene test</a></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#f-test"><i class="fa fa-check"></i>F-test</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#sample-size-calculation"><i class="fa fa-check"></i>Sample size calculation</a></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#lm---linear-models"><i class="fa fa-check"></i>LM - linear models</a></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#anova"><i class="fa fa-check"></i>Anova</a></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#ancova"><i class="fa fa-check"></i>Ancova</a>
<ul>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#approach"><i class="fa fa-check"></i>Approach</a></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#case-study"><i class="fa fa-check"></i>Case study</a></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#ancova-1"><i class="fa fa-check"></i>Ancova</a></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#comparison-with-anova"><i class="fa fa-check"></i>Comparison with anova</a></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#potential-applications"><i class="fa fa-check"></i>Potential applications</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html"><i class="fa fa-check"></i>DOE - Design of Experiments</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#two-factors-anova-fixed-effects-model"><i class="fa fa-check"></i>two-factors ANOVA, fixed effects model</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#battery-life-example"><i class="fa fa-check"></i>Battery life example</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#analysis-of-variance"><i class="fa fa-check"></i>Analysis of variance</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#doe-and-anova-plots"><i class="fa fa-check"></i>DoE and Anova plots</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#r²-coefficient-of-determination"><i class="fa fa-check"></i>R², coefficient of determination</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#model-adequacy-checking"><i class="fa fa-check"></i>Model adequacy checking</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#residuals-normality-check-outliers"><i class="fa fa-check"></i>Residuals normality check &amp; outliers</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#plot-of-residuals-versus-fitted-values"><i class="fa fa-check"></i>Plot of residuals versus fitted values</a></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#sample-size-calculation"><i class="fa fa-check"></i>Sample size calculation</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#model-with-no-interaction"><i class="fa fa-check"></i>Model with no interaction</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#general-factorial-design"><i class="fa fa-check"></i>General factorial design</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#soft-drink-bottling-example"><i class="fa fa-check"></i>Soft Drink bottling example</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#analysis-of-variance-1"><i class="fa fa-check"></i>Analysis of variance</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#residuals-analysis"><i class="fa fa-check"></i>Residuals analysis</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#doe-plots"><i class="fa fa-check"></i>DoE plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-2k-factorial-designs"><i class="fa fa-check"></i>The 2^k factorial designs</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-22-factorial-design"><i class="fa fa-check"></i>The 2^2 Factorial Design</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-chemical-process-example"><i class="fa fa-check"></i>The Chemical Process example</a></li>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#anova"><i class="fa fa-check"></i>Anova</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#correlation-of-the-outputs"><i class="fa fa-check"></i>Correlation of the outputs</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#correlation-matrix"><i class="fa fa-check"></i>Correlation matrix</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#network-diagrams"><i class="fa fa-check"></i>Network diagrams</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#regression-model-prediction"><i class="fa fa-check"></i>Regression model / Prediction</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#response-surface"><i class="fa fa-check"></i>Response surface</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-23-factorial-design"><i class="fa fa-check"></i>The 2^3 Factorial Design</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-plasma-etching-example"><i class="fa fa-check"></i>The plasma etching example</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#anova-1"><i class="fa fa-check"></i>Anova</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#regression-model-prediction-1"><i class="fa fa-check"></i>Regression model / Prediction</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#reduced-model"><i class="fa fa-check"></i>Reduced model</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#doe-plots-1"><i class="fa fa-check"></i>DoE plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-general-2k-design"><i class="fa fa-check"></i>The general 2^k design</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#calculating-the-number-combinations"><i class="fa fa-check"></i>Calculating the number combinations</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#relationship-coded-vs-natural-variables"><i class="fa fa-check"></i>Relationship coded vs natural variables</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#single-replicate-2k-design"><i class="fa fa-check"></i>Single replicate 2^k design</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-filtration-example"><i class="fa fa-check"></i>The Filtration example</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#anova-2"><i class="fa fa-check"></i>Anova</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#linear-regression---plot-of-effects"><i class="fa fa-check"></i>Linear regression - Plot of effects</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#doe-plots-2"><i class="fa fa-check"></i>DoE plots</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#anova-reduced-model-significant-effects-only"><i class="fa fa-check"></i>Anova reduced model (significant effects only)</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#linear-regression---reduced-model"><i class="fa fa-check"></i>Linear regression - reduced model</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#residuals-normality-check"><i class="fa fa-check"></i>Residuals normality check</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#two-level-fractional-factorial-designs"><i class="fa fa-check"></i>Two level fractional factorial designs</a>
<ul>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-one-half-fraction-of-th-2k-design"><i class="fa fa-check"></i>The One-Half Fraction of th 2k Design</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#the-filtration-example-modified"><i class="fa fa-check"></i>The filtration example (modified)</a></li>
<li class="chapter" data-level="" data-path="DOE.html"><a href="DOE.html#anova-3"><i class="fa fa-check"></i>Anova</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html"><i class="fa fa-check"></i>MSA - Measurement System Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html#robustness"><i class="fa fa-check"></i>Robustness</a></li>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html#linearity"><i class="fa fa-check"></i>Linearity</a></li>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html#loq---limit-of-quantification"><i class="fa fa-check"></i>LoQ - Limit of quantification</a></li>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html#trueness"><i class="fa fa-check"></i>Trueness</a></li>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html#gage-rr"><i class="fa fa-check"></i>Gage r&amp;R</a>
<ul>
<li class="chapter" data-level="" data-path="statistics.html"><a href="statistics.html#anova"><i class="fa fa-check"></i>Anova</a></li>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html#variance-components"><i class="fa fa-check"></i>Variance components</a></li>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html#measurement-uncertainty"><i class="fa fa-check"></i>Measurement uncertainty</a></li>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html#conclusions"><i class="fa fa-check"></i>Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="MSA.html"><a href="MSA.html#mu---measurement-incertainty"><i class="fa fa-check"></i>MU - Measurement incertainty</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="SPC.html"><a href="SPC.html"><i class="fa fa-check"></i>SPC - Statistical Process Control</a>
<ul>
<li class="chapter" data-level="" data-path="SPC.html"><a href="SPC.html#xbar-and-r-charts"><i class="fa fa-check"></i>xbar and R charts</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Cpk.html"><a href="Cpk.html"><i class="fa fa-check"></i>CPK - Process Capability Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="Cpk.html"><a href="Cpk.html#out-of-specification"><i class="fa fa-check"></i>Out of specification</a></li>
<li class="chapter" data-level="" data-path="Cpk.html"><a href="Cpk.html#process-histogram"><i class="fa fa-check"></i>Process histogram</a></li>
</ul></li>
<li class="part"><span><b>II TOOLBOX</b></span></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html"><i class="fa fa-check"></i>R</a>
<ul>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#why-r"><i class="fa fa-check"></i>Why R?</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-packages"><i class="fa fa-check"></i>R Packages</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#domain-packages"><i class="fa fa-check"></i>Domain packages</a>
<ul>
<li class="chapter" data-level="" data-path="six-sigma.html"><a href="six-sigma.html#six-sigma"><i class="fa fa-check"></i>six sigma</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#ggspc"><i class="fa fa-check"></i>ggspc</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#qcc"><i class="fa fa-check"></i>qcc</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#qicharts2"><i class="fa fa-check"></i>qicharts2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#other-packages"><i class="fa fa-check"></i>Other packages</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#session-info"><i class="fa fa-check"></i>Session info</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html"><i class="fa fa-check"></i>Datasets</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">indust<b style='color:#4775d1'>R</b>ial data science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistics" class="section level1">
<h1>Statistics</h1>
<p>In this chapter we’re going to review key statistical concepts used throughout this book. These will be presented in small contained examples serving more as a toolbox. They cover the</p>
<p><strong>Descriptive statistics</strong></p>
<ul>
<li>mean</li>
<li>median</li>
<li>mode</li>
<li>variance</li>
<li>standard deviation</li>
<li>range</li>
</ul>
<p><strong>Statistical distributions</strong></p>
<ul>
<li>Normal distribution</li>
<li>Central limit theorem</li>
<li>Confidence intervals</li>
</ul>
<p><strong>Statistical tests</strong></p>
<ul>
<li>comparing means</li>
<li>comparing variances</li>
<li>linear models</li>
<li>Anova</li>
<li>Ancova</li>
</ul>
<p><strong>Modeling</strong></p>
<ul>
<li>linear models</li>
</ul>
<p>We start by loading the first packages we will need:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="statistics.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb12-2"><a href="statistics.html#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb12-3"><a href="statistics.html#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb12-4"><a href="statistics.html#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="statistics.html#cb12-5" aria-hidden="true" tabindex="-1"></a>filter <span class="ot">&lt;-</span> dplyr<span class="sc">::</span>filter</span>
<span id="cb12-6"><a href="statistics.html#cb12-6" aria-hidden="true" tabindex="-1"></a>select <span class="ot">&lt;-</span> dplyr<span class="sc">::</span>select</span></code></pre></div>
<div id="comparing-means" class="section level2">
<h2>Comparing means</h2>
<div id="t-test-one-sample" class="section level3">
<h3>t-test one sample</h3>
<p>Comparing mean to specification</p>
<p>An engineer has established a contract for cement supply based on the following specification: the average bond strength has to be greater than 17.0 <span class="math inline">\(kgf/cm^2\)</span> for each delivery. In the contract is also specified that the test protocol which is based on a 30 samples.</p>
<p>A first delivery is submited and the customer wants to know if the lot average breaking strength exceeds the agreed bond level and if so, she wants to accept the lot.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="statistics.html#cb13-1" aria-hidden="true" tabindex="-1"></a>cement_delivery <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/2_cement_delivery.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   strength = col_double()
## )</code></pre>
<p>The Quality Control department specialist at the reception starts by calcultating the average, a first criteria to reject the batch:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="statistics.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(cement_delivery<span class="sc">$</span>strength)</span></code></pre></div>
<pre><code>## [1] 17.11607</code></pre>
<p>The average is above the spec so a next step is to observe the variability and for this she decides to plot the raw data on an histogram. An histogram is a very common plot showing counts for selected intervals.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="statistics.html#cb17-1" aria-hidden="true" tabindex="-1"></a>cement_delivery <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="statistics.html#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> strength)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="statistics.html#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">&quot;cadetblue&quot;</span>, <span class="at">color =</span> <span class="st">&quot;grey20&quot;</span>) <span class="sc">+</span></span>
<span id="cb17-4"><a href="statistics.html#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb17-5"><a href="statistics.html#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb17-6"><a href="statistics.html#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Cement mortar case study&quot;</span>,</span>
<span id="cb17-7"><a href="statistics.html#cb17-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Raw data plot&quot;</span>,</span>
<span id="cb17-8"><a href="statistics.html#cb17-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Treatment&quot;</span>,</span>
<span id="cb17-9"><a href="statistics.html#cb17-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Bond strength&quot;</span>)</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="stats_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>She observes a certain variability in the batch and decides to perform a t-test to assess if the average calculated can be considered statistically greater than the target value:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="statistics.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> cement_delivery<span class="sc">$</span>strength, <span class="at">mu =</span> <span class="dv">17</span>, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span></code></pre></div>
<pre><code>## 
## 	One Sample t-test
## 
## data:  cement_delivery$strength
## t = 1.3785, df = 27, p-value = 0.08968
## alternative hypothesis: true mean is greater than 17
## 95 percent confidence interval:
##  16.97266      Inf
## sample estimates:
## mean of x 
##  17.11607</code></pre>
<p>As the p value is much higher than the usual criteria of 0.05 thus she cannot cannot assume that the average strength of the batch is higher than 17. The batch is therefore rejected.</p>
</div>
<div id="t-test-two-samples" class="section level3">
<h3>t-test two samples</h3>
<p>Comparing means</p>
<p>In order to avoid similar situations in the future the development engineer considers a new chemical compositions of cement that potentially increases the levels of strenght.</p>
<p><strong>Data loading</strong></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="statistics.html#cb21-1" aria-hidden="true" tabindex="-1"></a>cement <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/2_cement.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Modified = col_double(),
##   Unmodified = col_double()
## )</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="statistics.html#cb23-1" aria-hidden="true" tabindex="-1"></a>cement_long <span class="ot">&lt;-</span> cement <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="statistics.html#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb23-3"><a href="statistics.html#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">&quot;treatment&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;y&quot;</span></span>
<span id="cb23-4"><a href="statistics.html#cb23-4" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p><strong>Raw data plot</strong></p>
<p>In data analysis it is good practice to start by plotting the raw data and have a first open look at what the first plots tell us.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="statistics.html#cb24-1" aria-hidden="true" tabindex="-1"></a>cement_long <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="statistics.html#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> treatment, <span class="at">y =</span> y, <span class="at">fill =</span> treatment)) <span class="sc">+</span></span>
<span id="cb24-3"><a href="statistics.html#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb24-4"><a href="statistics.html#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb24-5"><a href="statistics.html#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb24-6"><a href="statistics.html#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Cement mortar case study&quot;</span>,</span>
<span id="cb24-7"><a href="statistics.html#cb24-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Raw data plot&quot;</span>,</span>
<span id="cb24-8"><a href="statistics.html#cb24-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Treatment&quot;</span>,</span>
<span id="cb24-9"><a href="statistics.html#cb24-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Bond strength&quot;</span>)</span></code></pre></div>
<p><img src="stats_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Another way to better understanding the bond distributions is to plot a box plot. This type of plot is somehow like the histogram seen before but more compact when several groups are required to be plotted.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="statistics.html#cb25-1" aria-hidden="true" tabindex="-1"></a>cement_long <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="statistics.html#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> treatment, <span class="at">y =</span> y, <span class="at">fill =</span> treatment)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="statistics.html#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb25-4"><a href="statistics.html#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb25-5"><a href="statistics.html#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb25-6"><a href="statistics.html#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Cement mortar case study&quot;</span>,</span>
<span id="cb25-7"><a href="statistics.html#cb25-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Raw data plot&quot;</span>,</span>
<span id="cb25-8"><a href="statistics.html#cb25-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Treatment&quot;</span>,</span>
<span id="cb25-9"><a href="statistics.html#cb25-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Bond strength&quot;</span>)</span></code></pre></div>
<p><img src="stats_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>We would like to understand if the treatment has an effect. Thus we want to compare the two population means. For that we use a t test using samples obtained independently and randomly. Before running the test we also have to check the normality of the samples distributions and equality of their variances.</p>
<p>To do these checks we’re using the stat_qq functions from the ggplot package and plotting the qq plots for both levels in the same plot:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="statistics.html#cb26-1" aria-hidden="true" tabindex="-1"></a>cement_long <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="statistics.html#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> y, <span class="at">color =</span> treatment)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="statistics.html#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb26-4"><a href="statistics.html#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb26-5"><a href="statistics.html#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb26-6"><a href="statistics.html#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb26-7"><a href="statistics.html#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Cement mortar case study&quot;</span>,</span>
<span id="cb26-8"><a href="statistics.html#cb26-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Raw data plot&quot;</span>,</span>
<span id="cb26-9"><a href="statistics.html#cb26-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Treatment&quot;</span>,</span>
<span id="cb26-10"><a href="statistics.html#cb26-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Bond strength&quot;</span>)</span></code></pre></div>
<p><img src="stats_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>We observe that for both levels of treatment the data is adhering to the straight line thus we can assume they follow a normal distribution. Also both lines in the qq plot before have equivalent slopes indicating that the assumption of variances is a reasonable one. These verifications are summary ones. We review in subsequent sessions other deeper verifications of such as the shapiro-wilk normality test.</p>
<p>We’re now going to apply the t-test:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="statistics.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span></code></pre></div>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="statistics.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(y <span class="sc">~</span> treatment, <span class="at">data =</span> cement_long, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## 	Two Sample t-test
## 
## data:  y by treatment
## t = -2.1869, df = 18, p-value = 0.0422
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.54507339 -0.01092661
## sample estimates:
##   mean in group Modified mean in group Unmodified 
##                   16.764                   17.042</code></pre>
<p>We see that p &lt; 0.05 thus the means differ significantly. Furthemore the mean difference is estimated with 95% confidence, to be between -0.55 and -0.01 (to be noted that zero is obviously not included in this interval). There is an effect in our treatment that explains the difference in means between the two samples.</p>
</div>
<div id="t-test-two-samples-paired" class="section level3">
<h3>t-test two samples paired</h3>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="statistics.html#cb30-1" aria-hidden="true" tabindex="-1"></a>hardness <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/2_hardness.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Tip1 = col_double(),
##   Tip2 = col_double()
## )</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="statistics.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> hardness<span class="sc">$</span>Tip1, <span class="at">y =</span> hardness<span class="sc">$</span>Tip2, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## 	Paired t-test
## 
## data:  hardness$Tip1 and hardness$Tip2
## t = -0.26414, df = 9, p-value = 0.7976
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.9564389  0.7564389
## sample estimates:
## mean of the differences 
##                    -0.1</code></pre>
<p>p &gt; 0.05 thus the means cannot be considered different (we cannot reject the null hypothesis) The mean difference is with 95% confidence between -0.96 and 0.76.</p>
<p>Note that because it is paired although there are 20 measurements there are only 9 degrees of freedom (10 times the differences between the measurements, minus 1).</p>
<p>Randomization of the test sequence is a required practice, not only because of operator effects but also due to other potentially unknown effects like machine warm up.</p>
</div>
</div>
<div id="comparing-variances" class="section level2">
<h2>Comparing variances</h2>
<p>Bonett’s test is accurate for any continuous distribution and does not require that the data are normal. Bonett’s test is usually more reliable than Levene’s test.</p>
<p>Levene’s test is also accurate with any continuous distribution. For extremely skewed and heavy tailed distributions, Levene’s method tends to be more reliable than Bonett’s method.</p>
<p>The F-test is accurate only for normally distributed data. Any small deviation from normality can cause the F-test to be inaccurate, even with large samples. However, if the data conform well to the normal distribution, then the F-test is usually more powerful than either Bonett’s test or Levene’s test.</p>
<div id="bonetts-test" class="section level3">
<h3>Bonett’s test</h3>
</div>
<div id="levene-test" class="section level3">
<h3>Levene test</h3>
<p>Homogeneity of variances test</p>
<p>You want test samples to see for homogeneity of variance (homoscedasticity)</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="statistics.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<pre><code>## Le chargement a nécessité le package : carData</code></pre>
<pre><code>## 
## Attachement du package : &#39;car&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     recode</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     some</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="statistics.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(y <span class="sc">~</span> treatment, <span class="at">data =</span> cement_long)</span></code></pre></div>
<pre><code>## Warning in leveneTest.default(y = y, group = group, ...): group coerced to
## factor.</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  1  1.9528 0.1793
##       18</code></pre>
<p>Pr &gt; 0.05 thus there is homogeneity of the variances (they do not differ significantly).</p>
</div>
<div id="f-test" class="section level3">
<h3>F-test</h3>
<p>We’re now confirming this with a variance test from the stats package.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="statistics.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(y <span class="sc">~</span> treatment, cement_long)</span></code></pre></div>
<pre><code>## 
## 	F test to compare two variances
## 
## data:  y by treatment
## F = 1.6293, num df = 9, denom df = 9, p-value = 0.4785
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.4046845 6.5593806
## sample estimates:
## ratio of variances 
##           1.629257</code></pre>
<p>The test null hypothesis is that the variances are equal. Since the p value is much greater than 0.05 we cannot reject the null hypotheses meaning that we can consider them equal.</p>
<p>In other words the probability that the variances are different is 47.85% due to random cause.</p>
<ul>
<li>random sampling</li>
</ul>
</div>
</div>
<div id="sample-size-calculation" class="section level2">
<h2>Sample size calculation</h2>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="statistics.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the required sample size for a certain t-test power</span></span>
<span id="cb44-2"><a href="statistics.html#cb44-2" aria-hidden="true" tabindex="-1"></a>cohen_d <span class="ot">&lt;-</span> <span class="fl">0.27</span> <span class="sc">/</span> <span class="fl">0.25</span> <span class="co"># Cohen&#39;s effect size = difference of means / sd</span></span>
<span id="cb44-3"><a href="statistics.html#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="co"># A Cohen&#39;s d of 2 means that the averages changed by 2 standard deviations, which is very large.</span></span>
<span id="cb44-4"><a href="statistics.html#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">d =</span> cohen_d, <span class="at">power =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 23.28802
##           delta = 1.08
##              sd = 1
##       sig.level = 0.05
##           power = 0.95
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="statistics.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lsr)</span></code></pre></div>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="statistics.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># By comparison, calculate Cohen&#39;s d for the dataset</span></span>
<span id="cb47-2"><a href="statistics.html#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cohensD</span>(<span class="at">x =</span> cement<span class="sc">$</span>Modified, <span class="at">y =</span> cement<span class="sc">$</span>Unmodified)</span></code></pre></div>
<pre><code>## [1] 0.9780006</code></pre>
<p>In this example if we wanted to detect a significant difference of at least 0.25 in the means with a probability of at least 95% (Power of 0.95) we would need to use 8 (7.6) samples of each (to be)</p>

</div>
<div id="lm---linear-models" class="section level2">
<h2>LM - linear models</h2>
<p>Now we’re going to move into linear models with a first example. These models are going to be extensively used in the Case Studies namely in the Design of Experiments and in the Measurement System Analysis.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="statistics.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb49-2"><a href="statistics.html#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb49-3"><a href="statistics.html#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb49-4"><a href="statistics.html#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co"># library(readxl)</span></span>
<span id="cb49-5"><a href="statistics.html#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="co"># library(knitr)</span></span>
<span id="cb49-6"><a href="statistics.html#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="co"># library(car)</span></span>
<span id="cb49-7"><a href="statistics.html#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co"># library(pwr)</span></span>
<span id="cb49-8"><a href="statistics.html#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="co"># library(lsr)</span></span>
<span id="cb49-9"><a href="statistics.html#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="co"># library(broom)</span></span>
<span id="cb49-10"><a href="statistics.html#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="co"># library(RcmdrMisc)</span></span>
<span id="cb49-11"><a href="statistics.html#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="co"># library(agricolae)</span></span>
<span id="cb49-12"><a href="statistics.html#cb49-12" aria-hidden="true" tabindex="-1"></a>filter <span class="ot">&lt;-</span> dplyr<span class="sc">::</span>filter</span>
<span id="cb49-13"><a href="statistics.html#cb49-13" aria-hidden="true" tabindex="-1"></a>select <span class="ot">&lt;-</span> dplyr<span class="sc">::</span>select</span></code></pre></div>
<p><strong>Plasma etching example</strong></p>
<p>Data loading and cleansing:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="statistics.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Direct copy of the example from the book:</span></span>
<span id="cb50-2"><a href="statistics.html#cb50-2" aria-hidden="true" tabindex="-1"></a>plasma <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/3-1_plasma_etching.csv&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb50-3"><a href="statistics.html#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   power = col_double(),
##   `1` = col_double(),
##   `2` = col_double(),
##   `3` = col_double(),
##   `4` = col_double(),
##   `5` = col_double()
## )</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="statistics.html#cb52-1" aria-hidden="true" tabindex="-1"></a>plasma_narrow <span class="ot">&lt;-</span> plasma <span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="statistics.html#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb52-3"><a href="statistics.html#cb52-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">&quot;x&quot;</span>),</span>
<span id="cb52-4"><a href="statistics.html#cb52-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">&quot;observation&quot;</span>,</span>
<span id="cb52-5"><a href="statistics.html#cb52-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">&quot;etch_rate&quot;</span></span>
<span id="cb52-6"><a href="statistics.html#cb52-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>Raw data plot:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="statistics.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plasma_narrow, <span class="fu">aes</span>(<span class="at">x =</span> power, <span class="at">y =</span> etch_rate)) <span class="sc">+</span></span>
<span id="cb53-2"><a href="statistics.html#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb53-3"><a href="statistics.html#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb53-4"><a href="statistics.html#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb53-5"><a href="statistics.html#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Plasma case study&quot;</span>,</span>
<span id="cb53-6"><a href="statistics.html#cb53-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Raw data plot&quot;</span>,</span>
<span id="cb53-7"><a href="statistics.html#cb53-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Power&quot;</span>,</span>
<span id="cb53-8"><a href="statistics.html#cb53-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Etch rate&quot;</span>)</span></code></pre></div>
<p><img src="lm_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p><strong>Linear model</strong></p>
<p>Here we’re constructing a linear model of the raw data and not a model of the Anova, thus <em>power</em> has to be as integer and not as a factor, unlike in the Anova model.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="statistics.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span></code></pre></div>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="statistics.html#cb55-1" aria-hidden="true" tabindex="-1"></a>plasma_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(etch_rate <span class="sc">~</span> power, <span class="at">data =</span> plasma_narrow)</span>
<span id="cb55-2"><a href="statistics.html#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(plasma_lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = etch_rate ~ power, data = plasma_narrow)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -43.02 -12.32  -1.21  16.71  33.06 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 137.6200    41.2108   3.339  0.00365 ** 
## power         2.5270     0.2154  11.731 7.26e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.54 on 18 degrees of freedom
## Multiple R-squared:  0.8843,	Adjusted R-squared:  0.8779 
## F-statistic: 137.6 on 1 and 18 DF,  p-value: 7.263e-10</code></pre>
<p><strong>Linear regression plot</strong></p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="statistics.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plasma_narrow, <span class="fu">aes</span>(<span class="at">x =</span> power, <span class="at">y =</span> etch_rate)) <span class="sc">+</span></span>
<span id="cb57-2"><a href="statistics.html#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb57-3"><a href="statistics.html#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb57-4"><a href="statistics.html#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb57-5"><a href="statistics.html#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb57-6"><a href="statistics.html#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Plasma case study&quot;</span>,</span>
<span id="cb57-7"><a href="statistics.html#cb57-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Raw data plot&quot;</span>,</span>
<span id="cb57-8"><a href="statistics.html#cb57-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Power&quot;</span>,</span>
<span id="cb57-9"><a href="statistics.html#cb57-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Etch rate&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="lm_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p><strong>Predicting new values</strong></p>
<p>Here we’re using the model with power as an integer:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="statistics.html#cb59-1" aria-hidden="true" tabindex="-1"></a>power_new <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">power =</span> <span class="fu">c</span>(<span class="dv">170</span>, <span class="dv">190</span>))</span>
<span id="cb59-2"><a href="statistics.html#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(plasma_lm, <span class="at">newdata =</span> power_new)</span></code></pre></div>
<pre><code>##      1      2 
## 567.21 617.75</code></pre>
<p>** R², coefficient of determination</p>
<p>The R square can be extracted from the linear model that has been used to build the Anova model.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="statistics.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(plasma_lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = etch_rate ~ power, data = plasma_narrow)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -43.02 -12.32  -1.21  16.71  33.06 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 137.6200    41.2108   3.339  0.00365 ** 
## power         2.5270     0.2154  11.731 7.26e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.54 on 18 degrees of freedom
## Multiple R-squared:  0.8843,	Adjusted R-squared:  0.8779 
## F-statistic: 137.6 on 1 and 18 DF,  p-value: 7.263e-10</code></pre>
<p>Thus, in the plasma etching experiment, the factor “power” explains about 88% percent of the variability in etch rate.</p>
<p>pwr.anova.test(k = 4,
n = 2,
f = plasma_cohend_aov,
sig.level = 0.01)</p>
<p>Here I have not yet managed to reproduce the book example. See the example in chapter 5 where this has been successfull thus working as a better approach for the future.</p>

</div>
<div id="anova" class="section level2">
<h2>Anova</h2>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="statistics.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb63-2"><a href="statistics.html#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb63-3"><a href="statistics.html#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb63-4"><a href="statistics.html#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="co"># library(readxl)</span></span>
<span id="cb63-5"><a href="statistics.html#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="co"># library(knitr)</span></span>
<span id="cb63-6"><a href="statistics.html#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="co"># library(car)</span></span>
<span id="cb63-7"><a href="statistics.html#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="co"># library(pwr)</span></span>
<span id="cb63-8"><a href="statistics.html#cb63-8" aria-hidden="true" tabindex="-1"></a><span class="co"># library(lsr)</span></span>
<span id="cb63-9"><a href="statistics.html#cb63-9" aria-hidden="true" tabindex="-1"></a><span class="co"># library(broom)</span></span>
<span id="cb63-10"><a href="statistics.html#cb63-10" aria-hidden="true" tabindex="-1"></a><span class="co"># library(RcmdrMisc)</span></span>
<span id="cb63-11"><a href="statistics.html#cb63-11" aria-hidden="true" tabindex="-1"></a><span class="co"># library(agricolae)</span></span>
<span id="cb63-12"><a href="statistics.html#cb63-12" aria-hidden="true" tabindex="-1"></a>filter <span class="ot">&lt;-</span> dplyr<span class="sc">::</span>filter</span>
<span id="cb63-13"><a href="statistics.html#cb63-13" aria-hidden="true" tabindex="-1"></a>select <span class="ot">&lt;-</span> dplyr<span class="sc">::</span>select</span></code></pre></div>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="statistics.html#cb64-1" aria-hidden="true" tabindex="-1"></a>plasma <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/3-1_plasma_etching.csv&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb64-2"><a href="statistics.html#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   power = col_double(),
##   `1` = col_double(),
##   `2` = col_double(),
##   `3` = col_double(),
##   `4` = col_double(),
##   `5` = col_double()
## )</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="statistics.html#cb66-1" aria-hidden="true" tabindex="-1"></a>plasma_narrow <span class="ot">&lt;-</span> plasma <span class="sc">%&gt;%</span></span>
<span id="cb66-2"><a href="statistics.html#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb66-3"><a href="statistics.html#cb66-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">&quot;x&quot;</span>),</span>
<span id="cb66-4"><a href="statistics.html#cb66-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">&quot;observation&quot;</span>,</span>
<span id="cb66-5"><a href="statistics.html#cb66-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">&quot;etch_rate&quot;</span></span>
<span id="cb66-6"><a href="statistics.html#cb66-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>We can also compare medians and get a sense of the effect of the treatment levels by looking into the box plot:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="statistics.html#cb67-1" aria-hidden="true" tabindex="-1"></a>plasma_narrow_factor <span class="ot">&lt;-</span> plasma_narrow <span class="sc">%&gt;%</span></span>
<span id="cb67-2"><a href="statistics.html#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">power =</span> <span class="fu">as_factor</span>(power),</span>
<span id="cb67-3"><a href="statistics.html#cb67-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">observation =</span> <span class="fu">as_factor</span>(observation))</span></code></pre></div>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="statistics.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot</span></span>
<span id="cb68-2"><a href="statistics.html#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plasma_narrow_factor, <span class="fu">aes</span>(<span class="at">x =</span> power, <span class="at">y =</span> etch_rate)) <span class="sc">+</span></span>
<span id="cb68-3"><a href="statistics.html#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb68-4"><a href="statistics.html#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb68-5"><a href="statistics.html#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb68-6"><a href="statistics.html#cb68-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Plasma case study&quot;</span>,</span>
<span id="cb68-7"><a href="statistics.html#cb68-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Raw data plot&quot;</span>,</span>
<span id="cb68-8"><a href="statistics.html#cb68-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Power&quot;</span>,</span>
<span id="cb68-9"><a href="statistics.html#cb68-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Etch rate&quot;</span>)</span></code></pre></div>
<p><img src="anova_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>1 factor with severals levels + 1 continuous dependent variable
Similar to the t-test but extended - this test allows to compare the means between several levels of treatement for a continuous response variable (the t test is only 2 levels at a time, performing all pair wise t-tests would also not be a solution because its a lot of effort and would increase the type I error)</p>
<p>ANOVA principle: the total variability in the data, as measured by the total corrected sum of squares, can be partitioned into a sum of squares of the differences between the treatment averages and the grand average plus a sum of squares of the differences of observations within treatments from the treatment average</p>
<p><strong>Single factor, fixed effects model</strong></p>
<p>Anova on plasma etching example (ANOVA, single factor, fixed effects model)</p>
<p>In R the anova is built by passing the linear model to the anova or aov functions.
The output of the anova function is just the anova table as shown here for this first example. The output of the aov function is a list.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="statistics.html#cb69-1" aria-hidden="true" tabindex="-1"></a>plasma_lm_factor <span class="ot">&lt;-</span> <span class="fu">lm</span>(etch_rate <span class="sc">~</span> power, <span class="at">data =</span> plasma_narrow_factor)</span>
<span id="cb69-2"><a href="statistics.html#cb69-2" aria-hidden="true" tabindex="-1"></a>plasma_anova <span class="ot">&lt;-</span> <span class="fu">anova</span>(plasma_lm_factor)</span>
<span id="cb69-3"><a href="statistics.html#cb69-3" aria-hidden="true" tabindex="-1"></a>plasma_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(plasma_lm_factor)</span>
<span id="cb69-4"><a href="statistics.html#cb69-4" aria-hidden="true" tabindex="-1"></a>plasma_anova</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: etch_rate
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## power      3  66871 22290.2  66.797 2.883e-09 ***
## Residuals 16   5339   333.7                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="statistics.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(plasma_aov)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## power        3  66871   22290    66.8 2.88e-09 ***
## Residuals   16   5339     334                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>for interpretation of the F value see:</p>
<p><a href="https://blog.minitab.com/blog/adventures-in-statistics-2/understanding-analysis-of-variance-anova-and-the-f-test" class="uri">https://blog.minitab.com/blog/adventures-in-statistics-2/understanding-analysis-of-variance-anova-and-the-f-test</a></p>
<p>Note that the RF power or between-treatment mean square (22,290.18) is many times larger than the within-treatment or error mean square (333.70). This indicates that it is unlikely that the treatment means are equal.
Also p &lt; 0.05 thus we can reject the null hypothesis and conclude that the means are significantly different.</p>
<p>Anova on plasma etching, modification of the example to achieve a p &gt; 0.05:</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="statistics.html#cb73-1" aria-hidden="true" tabindex="-1"></a>plasma2 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/3-1_plasma_etching_2.csv&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb73-2"><a href="statistics.html#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   power = col_double(),
##   `1` = col_double(),
##   `2` = col_double(),
##   `3` = col_double(),
##   `4` = col_double(),
##   `5` = col_double()
## )</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="statistics.html#cb75-1" aria-hidden="true" tabindex="-1"></a>plasma2_narrow <span class="ot">&lt;-</span> <span class="fu">gather</span>(plasma2, </span>
<span id="cb75-2"><a href="statistics.html#cb75-2" aria-hidden="true" tabindex="-1"></a>                         observation, </span>
<span id="cb75-3"><a href="statistics.html#cb75-3" aria-hidden="true" tabindex="-1"></a>                         etch_rate, x1, x2, x3, x4, x5)</span>
<span id="cb75-4"><a href="statistics.html#cb75-4" aria-hidden="true" tabindex="-1"></a>plasma2_narrow_factor <span class="ot">&lt;-</span> plasma2_narrow</span>
<span id="cb75-5"><a href="statistics.html#cb75-5" aria-hidden="true" tabindex="-1"></a>plasma2_narrow_factor<span class="sc">$</span>power <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(plasma2_narrow_factor<span class="sc">$</span>power)</span>
<span id="cb75-6"><a href="statistics.html#cb75-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-7"><a href="statistics.html#cb75-7" aria-hidden="true" tabindex="-1"></a>plasma2_lm_factor <span class="ot">&lt;-</span> <span class="fu">lm</span>(etch_rate <span class="sc">~</span> power, <span class="at">data =</span> plasma2_narrow_factor)</span>
<span id="cb75-8"><a href="statistics.html#cb75-8" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(plasma2_lm_factor)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: etch_rate
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## power      3   1476   492.0  1.2015  0.341
## Residuals 16   6552   409.5</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="statistics.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plasma2_narrow_factor, <span class="fu">aes</span>(<span class="at">x =</span> power, <span class="at">y =</span> etch_rate)) <span class="sc">+</span></span>
<span id="cb77-2"><a href="statistics.html#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb77-3"><a href="statistics.html#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb77-4"><a href="statistics.html#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb77-5"><a href="statistics.html#cb77-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Plasma case study&quot;</span>,</span>
<span id="cb77-6"><a href="statistics.html#cb77-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Raw data plot&quot;</span>,</span>
<span id="cb77-7"><a href="statistics.html#cb77-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Power&quot;</span>,</span>
<span id="cb77-8"><a href="statistics.html#cb77-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Etch rate&quot;</span>)</span></code></pre></div>
<p><img src="anova_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>P &gt; 0.05 - there is no significant difference between the means</p>
<p><strong>Model adequacy check</strong></p>
<p><strong>Residuals normality check &amp; outliers</strong></p>
<p>Anova fixed effects assumes that:
- errors are normally distributed and are independent</p>
<p>As the number of residuals is too small we’re not checking the normality via the histogram but rather with a a Q-Q plot.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="statistics.html#cb78-1" aria-hidden="true" tabindex="-1"></a>plasma_lm_factor<span class="sc">$</span>residuals <span class="sc">%&gt;%</span></span>
<span id="cb78-2"><a href="statistics.html#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb78-3"><a href="statistics.html#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> value)) <span class="sc">+</span></span>
<span id="cb78-4"><a href="statistics.html#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb78-5"><a href="statistics.html#cb78-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb78-6"><a href="statistics.html#cb78-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb78-7"><a href="statistics.html#cb78-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb78-8"><a href="statistics.html#cb78-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb78-9"><a href="statistics.html#cb78-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Plasma case study&quot;</span>,</span>
<span id="cb78-10"><a href="statistics.html#cb78-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Residuals q-q plot&quot;</span>,</span>
<span id="cb78-11"><a href="statistics.html#cb78-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Sample quantiles&quot;</span>,</span>
<span id="cb78-12"><a href="statistics.html#cb78-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Theoretical Quantiles&quot;</span>)</span></code></pre></div>
<p><img src="anova_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The plot suggests normal distribution. The verification can be completed by a test. For populations &lt; 50 use the shapiro-wilk normality test.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="statistics.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(plasma_lm_factor<span class="sc">$</span>residuals)</span></code></pre></div>
<pre><code>## 
## 	Shapiro-Wilk normality test
## 
## data:  plasma_lm_factor$residuals
## W = 0.93752, p-value = 0.2152</code></pre>
<p>p &gt; 0.05 indicates that the residuals do not differ significantly from a normally distributed population.</p>
<p><strong>Standardized residuals graph</strong></p>
<p>A second graph shows that the standardised residuals are normally distributed (explanation in a later chunk).
This specific Standardize residuals graph also help detecting outliers in the residuals (any residual &gt; 3 standard deviations is a potential outlier).</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="statistics.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plasma_aov, <span class="at">which =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="anova_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p><strong>Plot of residuals in time sequence</strong></p>
<p>A tendency to have runs of positive of negative results indicates that the independency assumption does not hold.</p>
<p>Such plot needs that the order of data collection is available in the dataframe. In the example below this is NOT the case as the residuals from the model are sequenced as they appear in the <em>plasma</em> dataframe.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="statistics.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plasma2_lm_factor<span class="sc">$</span>residuals)</span></code></pre></div>
<p><img src="anova_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p><strong>Plot of residuals versus fitted values</strong></p>
<p>If the model is correct and the assumptions hold, the residuals should be structureless. This plot should not reveal any obvious pattern.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="statistics.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plasma_aov, <span class="at">which =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="anova_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p><strong>Equality of variances test (Barlett’s test)</strong></p>
<p>In the plasma etch experiment, the normality assumption is not in question, so we can apply Bartlett’s test to the etch
rate data.</p>
<p>(Bartlett’s test is very sensitive to the normality assumption. Consequently, when the validity of this assumption is doubtful, Bartlett’s test should not be used. In this case use the Modified Levene test).</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="statistics.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(etch_rate <span class="sc">~</span> power, <span class="at">data =</span> plasma_narrow)</span></code></pre></div>
<pre><code>## 
## 	Bartlett test of homogeneity of variances
## 
## data:  etch_rate by power
## Bartlett&#39;s K-squared = 0.43349, df = 3, p-value = 0.9332</code></pre>
<p>The P-value is P = 0.934, so we cannot reject the null hypothesis. There is no evidence to counter the claim that all five variances are the same. This is the same conclusion reached by analyzing the plot of residuals versus fitted values.</p>
<p><strong>Tuckey’s pairwise comparison test</strong></p>
<p>The Anova may indicate that the treament means differ but it won’t indicate which ones. In this case we may want to compare pairs of means.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="statistics.html#cb86-1" aria-hidden="true" tabindex="-1"></a>plasma_tukey <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(plasma_aov, <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb86-2"><a href="statistics.html#cb86-2" aria-hidden="true" tabindex="-1"></a>plasma_tukey</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
##     factor levels have been ordered
## 
## Fit: aov(formula = plasma_lm_factor)
## 
## $power
##          diff        lwr       upr     p adj
## 180-160  36.2   3.145624  69.25438 0.0294279
## 200-160  74.2  41.145624 107.25438 0.0000455
## 220-160 155.8 122.745624 188.85438 0.0000000
## 200-180  38.0   4.945624  71.05438 0.0215995
## 220-180 119.6  86.545624 152.65438 0.0000001
## 220-200  81.6  48.545624 114.65438 0.0000146</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="statistics.html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plasma_tukey)</span></code></pre></div>
<p><img src="anova_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>The differences reproduce exactly the book example.</p>
<p>My conclusion is that for all differences p &lt; 0.05, thus all differences are significantly different.
Therefore, each power setting results in a mean etch rate that differs from the mean etch rate at any other power setting.</p>
<p><strong>Fisher’s LSD - pairwise comparison test</strong></p>
<p>Fisher’s Least Significant difference is an alternative to Tuckey’s test.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="statistics.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(agricolae)</span></code></pre></div>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="statistics.html#cb90-1" aria-hidden="true" tabindex="-1"></a>plasma_LSD <span class="ot">&lt;-</span> <span class="fu">LSD.test</span>(<span class="at">y =</span> plasma_narrow_factor<span class="sc">$</span>etch_rate,</span>
<span id="cb90-2"><a href="statistics.html#cb90-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">trt =</span> plasma_narrow_factor<span class="sc">$</span>power,</span>
<span id="cb90-3"><a href="statistics.html#cb90-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">DFerror =</span> plasma_anova<span class="sc">$</span>Df[<span class="dv">2</span>],  </span>
<span id="cb90-4"><a href="statistics.html#cb90-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">MSerror =</span> plasma_anova<span class="sc">$</span><span class="st">`</span><span class="at">Mean Sq</span><span class="st">`</span>[<span class="dv">2</span>],</span>
<span id="cb90-5"><a href="statistics.html#cb90-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">alpha =</span> <span class="fl">0.05</span>)</span>
<span id="cb90-6"><a href="statistics.html#cb90-6" aria-hidden="true" tabindex="-1"></a>plasma_LSD</span></code></pre></div>
<pre><code>## $statistics
##   MSerror Df   Mean       CV  t.value      LSD
##     333.7 16 617.75 2.957095 2.119905 24.49202
## 
## $parameters
##         test p.ajusted                     name.t ntr alpha
##   Fisher-LSD      none plasma_narrow_factor$power   4  0.05
## 
## $means
##     plasma_narrow_factor$etch_rate      std r      LCL      UCL Min Max Q25 Q50
## 160                          551.2 20.01749 5 533.8815 568.5185 530 575 539 542
## 180                          587.4 16.74216 5 570.0815 604.7185 565 610 579 590
## 200                          625.4 20.52559 5 608.0815 642.7185 600 651 610 629
## 220                          707.0 15.24795 5 689.6815 724.3185 685 725 700 710
##     Q75
## 160 570
## 180 593
## 200 637
## 220 715
## 
## $comparison
## NULL
## 
## $groups
##     plasma_narrow_factor$etch_rate groups
## 220                          707.0      a
## 200                          625.4      b
## 180                          587.4      c
## 160                          551.2      d
## 
## attr(,&quot;class&quot;)
## [1] &quot;group&quot;</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="statistics.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plasma_LSD)</span></code></pre></div>
<p><img src="anova_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Although the LSD value output from the test doesn’t match exactly the book value of 33.09 the conclusion is the same and can be interpreted from the fact that all means are in different groups (different letters).</p>
<p><strong>Sample size calculation</strong></p>
<p>Refer to “Statistiques faciles avec R,” page 233.
Cohen’s effect size is calculated with the eta squared from the model (intriguing is the same value as the R²…).
In this case with 2 replicates we obtain a power of 90% and an alpha of 1%.
I’ve not managed here to replicate the values from the Montgomery book.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="statistics.html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pwr)</span>
<span id="cb93-2"><a href="statistics.html#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lsr)</span></code></pre></div>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="statistics.html#cb94-1" aria-hidden="true" tabindex="-1"></a>plasma_eta2 <span class="ot">&lt;-</span> <span class="fu">etaSquared</span>(plasma_aov)[<span class="dv">1</span>]</span>
<span id="cb94-2"><a href="statistics.html#cb94-2" aria-hidden="true" tabindex="-1"></a>plasma_cohend_aov <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(plasma_eta2 <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> plasma_eta2))</span></code></pre></div>

</div>
<div id="ancova" class="section level2">
<h2>Ancova</h2>
<p>We assess here the potential utilisation of the analysis of covariance (ancova) in situations where a continuous variable may be influencing the measured value. This technique complements the analysis of variance (anova) allowing for a more accurate assessment of the effects of the categorical variables.</p>
<div id="approach" class="section level3">
<h3>Approach</h3>
<p>Below a description of the approach taken from <span class="citation">(<a href="references.html#ref-Montgomery2012" role="doc-biblioref">Montgomery 2012</a>)</span>, pag.655:</p>
<p><em>Suppose that in an experiment with a response variable y there is another variable, say x, and that y is linearly related to x. Furthermore, suppose that x cannot be controlled by the experimenter but can be observed along with y. The variable x is called a covariate or concomitant variable. The analysis of covariance involves adjusting the observed response variable for the effect of the concomitant variable.</em></p>
<p><em>If such an adjustment is not performed, the concomitant variable could inflate the error mean square and make true differences in the response due to treatments harder to detect. Thus, the analysis of covariance is a method of adjusting for the effects of an uncontrollable nuisance variable. As we will see, the procedure is a combination of analysis of variance and regression analysis.</em></p>
<p><em>As an example of an experiment in which the analysis of covariance may be employed, consider a study performed to determine if there is a difference in the strength of a monofilament fiber produced by three different machines. The data from this experiment are shown in Table 15.10 (below). Figure 15.3 presents a scatter diagram of strength (y) versus the diameter (or thickness) of the sample. Clearly, the strength of the fiber is also affected by its thickness; consequently, a thicker fiber will generally be stronger than a thinner one. The analysis of covariance could be used to remove the effect of thickness (x) on strength (y) when testing for differences in strength between machines.</em></p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="statistics.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## -- Attaching packages -------------------------------------- tidyverse 1.3.0 --</code></pre>
<pre><code>## v ggplot2 3.3.2     v purrr   0.3.4
## v tibble  3.0.3     v dplyr   1.0.2
## v tidyr   1.1.1     v stringr 1.4.0
## v readr   1.3.1     v forcats 0.5.0</code></pre>
<pre><code>## </code></pre>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="statistics.html#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb99-2"><a href="statistics.html#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb99-3"><a href="statistics.html#cb99-3" aria-hidden="true" tabindex="-1"></a>filter <span class="ot">&lt;-</span> dplyr<span class="sc">::</span>filter</span>
<span id="cb99-4"><a href="statistics.html#cb99-4" aria-hidden="true" tabindex="-1"></a>select <span class="ot">&lt;-</span> dplyr<span class="sc">::</span>select</span></code></pre></div>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="statistics.html#cb100-1" aria-hidden="true" tabindex="-1"></a>filament <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;data/filament.xlsx&quot;</span>)</span>
<span id="cb100-2"><a href="statistics.html#cb100-2" aria-hidden="true" tabindex="-1"></a>filament <span class="sc">%&gt;%</span> </span>
<span id="cb100-3"><a href="statistics.html#cb100-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">machine</th>
<th align="right">strength</th>
<th align="right">thickness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">m1</td>
<td align="right">36</td>
<td align="right">20</td>
</tr>
<tr class="even">
<td align="left">m1</td>
<td align="right">41</td>
<td align="right">25</td>
</tr>
<tr class="odd">
<td align="left">m1</td>
<td align="right">39</td>
<td align="right">24</td>
</tr>
<tr class="even">
<td align="left">m1</td>
<td align="right">42</td>
<td align="right">25</td>
</tr>
<tr class="odd">
<td align="left">m1</td>
<td align="right">49</td>
<td align="right">32</td>
</tr>
<tr class="even">
<td align="left">m2</td>
<td align="right">40</td>
<td align="right">22</td>
</tr>
<tr class="odd">
<td align="left">m2</td>
<td align="right">48</td>
<td align="right">28</td>
</tr>
<tr class="even">
<td align="left">m2</td>
<td align="right">39</td>
<td align="right">22</td>
</tr>
<tr class="odd">
<td align="left">m2</td>
<td align="right">45</td>
<td align="right">30</td>
</tr>
<tr class="even">
<td align="left">m2</td>
<td align="right">44</td>
<td align="right">28</td>
</tr>
<tr class="odd">
<td align="left">m3</td>
<td align="right">35</td>
<td align="right">21</td>
</tr>
<tr class="even">
<td align="left">m3</td>
<td align="right">37</td>
<td align="right">23</td>
</tr>
<tr class="odd">
<td align="left">m3</td>
<td align="right">42</td>
<td align="right">26</td>
</tr>
<tr class="even">
<td align="left">m3</td>
<td align="right">34</td>
<td align="right">21</td>
</tr>
<tr class="odd">
<td align="left">m3</td>
<td align="right">32</td>
<td align="right">15</td>
</tr>
</tbody>
</table>
<p>Below a plot of strenght by thickness:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="statistics.html#cb101-1" aria-hidden="true" tabindex="-1"></a>filament <span class="sc">%&gt;%</span></span>
<span id="cb101-2"><a href="statistics.html#cb101-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> thickness, <span class="at">y =</span> strength)) <span class="sc">+</span></span>
<span id="cb101-3"><a href="statistics.html#cb101-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb101-4"><a href="statistics.html#cb101-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb101-5"><a href="statistics.html#cb101-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Computation failed in `stat_smooth()`:
## objet &#39;lm&#39; de mode &#39;function&#39; introuvable</code></pre>
<p><img src="ancova_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="statistics.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># as the plot is slightly different from the book, the plot below has been done </span></span>
<span id="cb104-2"><a href="statistics.html#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="co"># in base R just to confirm and we get exactly the sameas  with ggplot2.</span></span>
<span id="cb104-3"><a href="statistics.html#cb104-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb104-4"><a href="statistics.html#cb104-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(filament<span class="sc">$</span>thickness, filament<span class="sc">$</span>strength)</span>
<span id="cb104-5"><a href="statistics.html#cb104-5" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(jitter(filament$strength, 1), jitter(filament$thickness, 1))</span></span>
<span id="cb104-6"><a href="statistics.html#cb104-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(strength<span class="sc">~</span>thickness, <span class="at">data =</span> filament))</span></code></pre></div>
<p>And a short test to assess the strenght of the correlation:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="statistics.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span></code></pre></div>
<pre><code>## 
## Attachement du package : &#39;stats&#39;</code></pre>
<pre><code>## The following object is masked _by_ &#39;.GlobalEnv&#39;:
## 
##     filter</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     filter, lag</code></pre>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="statistics.html#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(filament<span class="sc">$</span>strength, filament<span class="sc">$</span>thickness)</span></code></pre></div>
<pre><code>## 
## 	Pearson&#39;s product-moment correlation
## 
## data:  filament$strength and filament$thickness
## t = 9.8039, df = 13, p-value = 2.263e-07
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.8209993 0.9797570
## sample estimates:
##      cor 
## 0.938542</code></pre>
<p>Going further and using the approach from <span class="citation">(<a href="references.html#ref-Broc2016" role="doc-biblioref">Broc 2016</a>)</span> I’m faceting the scatterplots to assess if the coefficient of the linear regression is similar for all the levels of the machine factor:</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="statistics.html#cb111-1" aria-hidden="true" tabindex="-1"></a>filament <span class="sc">%&gt;%</span></span>
<span id="cb111-2"><a href="statistics.html#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> thickness, <span class="at">y =</span> strength)) <span class="sc">+</span></span>
<span id="cb111-3"><a href="statistics.html#cb111-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb111-4"><a href="statistics.html#cb111-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb111-5"><a href="statistics.html#cb111-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="at">facets =</span> <span class="st">&quot;machine&quot;</span>) <span class="sc">+</span></span>
<span id="cb111-6"><a href="statistics.html#cb111-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="ancova_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Visually this is the case, going from one level to the other is not changing the relationship between thickness and strenght - increasing thickness increases stenght. Visually the slopes are similar but the number of points is small. In a real case this verification could be extended with the correlation test for each level or/and a statistical test between slopes.</p>
</div>
<div id="case-study" class="section level3">
<h3>Case study</h3>
<p>We’re now reproducing in R the ancova case study from the book, still using the aov function.</p>
<p>The way to feed the R function arguments is obtained from <a href="https://www.datanovia.com/en/lessons/ancova-in-r/" class="uri">https://www.datanovia.com/en/lessons/ancova-in-r/</a></p>
<p>Note that in the formula the covariate goes first (and there is no interaction)! If you do not do this in order, you will get different results.</p>
</div>
<div id="ancova-1" class="section level3">
<h3>Ancova</h3>
<p><em>Three different machines produce a monofilament fiber for a textile company. The process engineer is interested in determining if there is a difference in the breaking strength of the fiber produced by the three machines. However, the strength of a fiber is related to its diameter, with thicker fibers being generally stronger than thinner ones. A random sample of five fiber specimens is selected from each machine.</em></p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="statistics.html#cb113-1" aria-hidden="true" tabindex="-1"></a>filament_ancova <span class="ot">&lt;-</span> <span class="fu">aov</span>(strength <span class="sc">~</span> thickness  <span class="sc">+</span> machine, filament)</span>
<span id="cb113-2"><a href="statistics.html#cb113-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(filament_ancova)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## thickness    1 305.13  305.13 119.933 2.96e-07 ***
## machine      2  13.28    6.64   2.611    0.118    
## Residuals   11  27.99    2.54                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>All values from the book table page 662 are correctly obtained with the code above. In particular:</p>
<ul>
<li>machine in this table corresponds to the adjusted machines mean square</li>
<li>residuals in this table corresponds to the error</li>
</ul>
<p>to be noted that the R anova table gives the thickness meansquare while the book doesn’t.</p>
<p>Conclusions from the book in page 662:</p>
<p><em>Comparing the adjusted treatment means with the unadjusted treatment means (the y i. ), we note that the adjusted means are much closer together, another indication that the covariance analysis was necessary.</em></p>
<p><em>A basic assumption in the analysis of covariance is that the treatments do not influence the covariate x because the technique removes the effect of variations in the x i. . However, if the variability in the x i. is due in part to the treatments, then analysis of covariance removes part of the treatment effect. Thus, we must be reasonably sure that the treatments do not affect the values x ij.</em></p>
<p><em>In some experiments this may be obvious from the nature of the covariate, whereas in others it may be more doubtful. In our example, there may be a difference in fiber diameter (x ij ) between the three machines. In such cases, Cochran and Cox (1957) suggest that an analysis of variance on the x ij values may be helpful in determining the validity of this assumption. …there is no reason to believe that machines produce fibers of different diameters.</em></p>
<p>(I did not go further here as it goes beyond the scope of the assessment)</p>
</div>
<div id="comparison-with-anova" class="section level3">
<h3>Comparison with anova</h3>
<p>Below I’m doing the common approach we’ve been using at NSTC in design of experiments.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="statistics.html#cb115-1" aria-hidden="true" tabindex="-1"></a>filament_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(strength <span class="sc">~</span> machine, filament)</span>
<span id="cb115-2"><a href="statistics.html#cb115-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(filament_aov)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)  
## machine      2  140.4   70.20   4.089 0.0442 *
## Residuals   12  206.0   17.17                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The anova table obtained also corresponds correctly to the book example.</p>
<p>Montgomery final observations:</p>
<p><em>It is interesting to note what would have happened in this experiment if an analysis of covariance had not been performed, that is, if the breaking strength data (y) had been analyzed as a completely randomized single-factor experiment in which the covariate x was ignored. The analysis of variance of the breaking strength data is shown in Table 15.14. We immediately notice that the error estimate is much longer in the CRD analysis (17.17 versus 2.54). This is a reflection of the effectiveness of analysis of covariance in reducing error variability.</em></p>
<p><em>We would also conclude, based on the CRD analysis, that machines differ significantly in the strength of fiber produced. This is exactly opposite the conclusion reached by the covariance analysis.</em></p>
<p><em>If we suspected that the machines differed significantly in their effect on fiber strength, then we would try to equalize the strength output of the three machines. However, in this problem the machines do not differ in the strength of fiber produced after the linear effect of fiber diameter is removed. It would be helpful to reduce the within-machine fiber diameter variability because this would probably reduce the strength variability in the fiber.</em></p>
</div>
<div id="potential-applications" class="section level3">
<h3>Potential applications</h3>
<p>In the scope of methods validations this approach could potentially be used in robustness validations when there is suspiction that a continuous variable is disturbing the measurement.</p>
<p>Naturally this should not be applied everywhere but only where there would to be logical a physical or chemical reason behind as in the example with thickness and strenght.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="six-sigma.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="DOE.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
